(function(){
  'use strict';

  // Saygı seçkisi: sıra sabittir; app.js yerel gün anahtarıyla her gün tek bir kişiyi seçer.
  // trTitle bulunamazsa enTitle, Wikipedia veri hattında güvenli geri dönüş olarak kullanılır.
  window.SaygiPeople=[
    {id:'ada-lovelace',name:'Ada Lovelace',trTitle:'Ada Lovelace',enTitle:'Ada Lovelace',field:'Matematik · Bilgisayar bilimi',kind:'Bilim',era:'1815–1852'},
    {id:'albert-einstein',name:'Albert Einstein',trTitle:'Albert Einstein',enTitle:'Albert Einstein',field:'Fizik',kind:'Bilim',era:'1879–1955'},
    {id:'alan-turing',name:'Alan Turing',trTitle:'Alan Turing',enTitle:'Alan Turing',field:'Matematik · Bilgisayar bilimi',kind:'Bilim',era:'1912–1954'},
    {id:'alexander-fleming',name:'Alexander Fleming',trTitle:'Alexander Fleming',enTitle:'Alexander Fleming',field:'Tıp · Bakteriyoloji',kind:'Bilim',era:'1881–1955'},
    {id:'archimedes',name:'Arşimet',trTitle:'Arşimet',enTitle:'Archimedes',field:'Matematik · Mühendislik',kind:'Bilim',era:'MÖ 287–212'},
    {id:'aristotle',name:'Aristoteles',trTitle:'Aristoteles',enTitle:'Aristotle',field:'Doğa felsefesi · Mantık',kind:'Bilim',era:'MÖ 384–322'},
    {id:'aryabhata',name:'Aryabhata',trTitle:'Aryabhata',enTitle:'Aryabhata',field:'Matematik · Astronomi',kind:'Bilim',era:'476–550'},
    {id:'aziz-sancar',name:'Aziz Sancar',trTitle:'Aziz Sancar',enTitle:'Aziz Sancar',field:'Biyokimya',kind:'Bilim',era:'1946–'},
    {id:'barbara-mcclintock',name:'Barbara McClintock',trTitle:'Barbara McClintock',enTitle:'Barbara McClintock',field:'Genetik',kind:'Bilim',era:'1902–1992'},
    {id:'carl-sagan',name:'Carl Sagan',trTitle:'Carl Sagan',enTitle:'Carl Sagan',field:'Astronomi · Bilim iletişimi',kind:'Bilim',era:'1934–1996'},
    {id:'cahit-arf',name:'Cahit Arf',trTitle:'Cahit Arf',enTitle:'Cahit Arf',field:'Matematik',kind:'Bilim',era:'1910–1997'},
    {id:'charles-darwin',name:'Charles Darwin',trTitle:'Charles Darwin',enTitle:'Charles Darwin',field:'Doğa tarihi · Evrimsel biyoloji',kind:'Bilim',era:'1809–1882'},
    {id:'chien-shiung-wu',name:'Chien-Shiung Wu',trTitle:'Chien-Shiung Wu',enTitle:'Chien-Shiung Wu',field:'Deneysel fizik',kind:'Bilim',era:'1912–1997'},
    {id:'claude-shannon',name:'Claude Shannon',trTitle:'Claude Shannon',enTitle:'Claude Shannon',field:'Bilgi kuramı',kind:'Bilim',era:'1916–2001'},
    {id:'dorothy-hodgkin',name:'Dorothy Hodgkin',trTitle:'Dorothy Hodgkin',enTitle:'Dorothy Hodgkin',field:'Kimya · Kristalografi',kind:'Bilim',era:'1910–1994'},
    {id:'feza-gursey',name:'Feza Gürsey',trTitle:'Feza Gürsey',enTitle:'Feza Gürsey',field:'Kuramsal fizik',kind:'Bilim',era:'1921–1992'},
    {id:'francis-crick',name:'Francis Crick',trTitle:'Francis Crick',enTitle:'Francis Crick',field:'Moleküler biyoloji',kind:'Bilim',era:'1916–2004'},
    {id:'galileo',name:'Galileo Galilei',trTitle:'Galileo Galilei',enTitle:'Galileo Galilei',field:'Astronomi · Fizik',kind:'Bilim',era:'1564–1642'},
    {id:'gazi-yasargil',name:'Gazi Yaşargil',trTitle:'Gazi Yaşargil',enTitle:'Gazi Yaşargil',field:'Beyin cerrahisi',kind:'Bilim',era:'1925–'},
    {id:'georges-lemaitre',name:'Georges Lemaître',trTitle:'Georges Lemaître',enTitle:'Georges Lemaître',field:'Kozmoloji · Fizik',kind:'Bilim',era:'1894–1966'},
    {id:'grace-hopper',name:'Grace Hopper',trTitle:'Grace Hopper',enTitle:'Grace Hopper',field:'Bilgisayar bilimi',kind:'Bilim',era:'1906–1992'},
    {id:'gregor-mendel',name:'Gregor Mendel',trTitle:'Gregor Mendel',enTitle:'Gregor Mendel',field:'Genetik',kind:'Bilim',era:'1822–1884'},
    {id:'hedy-lamarr',name:'Hedy Lamarr',trTitle:'Hedy Lamarr',enTitle:'Hedy Lamarr',field:'Mucitlik · İletişim teknolojisi',kind:'Bilim',era:'1914–2000'},
    {id:'hypatia',name:'Hypatia',trTitle:'Hypatia',enTitle:'Hypatia',field:'Matematik · Astronomi',kind:'Bilim',era:'yaklaşık 355–415'},
    {id:'ibn-al-haytham',name:'İbnü’l-Heysem',trTitle:"İbnü'l-Heysem",enTitle:'Ibn al-Haytham',field:'Optik · Matematik',kind:'Bilim',era:'965–1040'},
    {id:'ibn-sina',name:'İbn Sina',trTitle:'İbn-i Sina',enTitle:'Avicenna',field:'Tıp · Felsefe',kind:'Bilim',era:'980–1037'},
    {id:'isaac-newton',name:'Isaac Newton',trTitle:'Isaac Newton',enTitle:'Isaac Newton',field:'Fizik · Matematik',kind:'Bilim',era:'1643–1727'},
    {id:'jane-goodall',name:'Jane Goodall',trTitle:'Jane Goodall',enTitle:'Jane Goodall',field:'Primatoloji · Etoloji',kind:'Bilim',era:'1934–'},
    {id:'johannes-kepler',name:'Johannes Kepler',trTitle:'Johannes Kepler',enTitle:'Johannes Kepler',field:'Astronomi · Matematik',kind:'Bilim',era:'1571–1630'},
    {id:'katherine-johnson',name:'Katherine Johnson',trTitle:'Katherine Johnson',enTitle:'Katherine Johnson',field:'Matematik · Uzay bilimi',kind:'Bilim',era:'1918–2020'},
    {id:'louis-pasteur',name:'Louis Pasteur',trTitle:'Louis Pasteur',enTitle:'Louis Pasteur',field:'Mikrobiyoloji · Kimya',kind:'Bilim',era:'1822–1895'},
    {id:'lise-meitner',name:'Lise Meitner',trTitle:'Lise Meitner',enTitle:'Lise Meitner',field:'Nükleer fizik',kind:'Bilim',era:'1878–1968'},
    {id:'marie-curie',name:'Marie Curie',trTitle:'Marie Curie',enTitle:'Marie Curie',field:'Fizik · Kimya',kind:'Bilim',era:'1867–1934'},
    {id:'mary-anning',name:'Mary Anning',trTitle:'Mary Anning',enTitle:'Mary Anning',field:'Paleontoloji',kind:'Bilim',era:'1799–1847'},
    {id:'michael-faraday',name:'Michael Faraday',trTitle:'Michael Faraday',enTitle:'Michael Faraday',field:'Fizik · Kimya',kind:'Bilim',era:'1791–1867'},
    {id:'nikola-tesla',name:'Nikola Tesla',trTitle:'Nikola Tesla',enTitle:'Nikola Tesla',field:'Mühendislik · Elektrik',kind:'Bilim',era:'1856–1943'},
    {id:'niels-bohr',name:'Niels Bohr',trTitle:'Niels Bohr',enTitle:'Niels Bohr',field:'Kuantum fiziği',kind:'Bilim',era:'1885–1962'},
    {id:'oktay-sinanoglu',name:'Oktay Sinanoğlu',trTitle:'Oktay Sinanoğlu',enTitle:'Oktay Sinanoğlu',field:'Kimya · Moleküler biyoloji',kind:'Bilim',era:'1935–2015'},
    {id:'piri-reis',name:'Piri Reis',trTitle:'Piri Reis',enTitle:'Piri Reis',field:'Kartografya · Denizcilik',kind:'Bilim',era:'yaklaşık 1465–1553'},
    {id:'rachel-carson',name:'Rachel Carson',trTitle:'Rachel Carson',enTitle:'Rachel Carson',field:'Biyoloji · Çevre bilimi',kind:'Bilim',era:'1907–1964'},
    {id:'rosalind-franklin',name:'Rosalind Franklin',trTitle:'Rosalind Franklin',enTitle:'Rosalind Franklin',field:'Kimya · Biyofizik',kind:'Bilim',era:'1920–1958'},
    {id:'ramanujan',name:'Srinivasa Ramanujan',trTitle:'Srinivasa Ramanujan',enTitle:'Srinivasa Ramanujan',field:'Matematik',kind:'Bilim',era:'1887–1920'},
    {id:'stephen-hawking',name:'Stephen Hawking',trTitle:'Stephen Hawking',enTitle:'Stephen Hawking',field:'Kozmoloji · Fizik',kind:'Bilim',era:'1942–2018'},
    {id:'tu-youyou',name:'Tu Youyou',trTitle:'Tu Youyou',enTitle:'Tu Youyou',field:'Farmakoloji',kind:'Bilim',era:'1930–'},
    {id:'vera-rubin',name:'Vera Rubin',trTitle:'Vera Rubin',enTitle:'Vera Rubin',field:'Astronomi',kind:'Bilim',era:'1928–2016'},
    {id:'williamina-fleming',name:'Williamina Fleming',trTitle:'Williamina Fleming',enTitle:'Williamina Fleming',field:'Astronomi',kind:'Bilim',era:'1857–1911'},
    {id:'w-e-b-du-bois',name:'W. E. B. Du Bois',trTitle:'W. E. B. Du Bois',enTitle:'W. E. B. Du Bois',field:'Sosyoloji · Tarih',kind:'Bilim',era:'1868–1963'},
    {id:'emmy-noether',name:'Emmy Noether',trTitle:'Emmy Noether',enTitle:'Emmy Noether',field:'Matematik · Fizik',kind:'Bilim',era:'1882–1935'},
    {id:'james-clerk-maxwell',name:'James Clerk Maxwell',trTitle:'James Clerk Maxwell',enTitle:'James Clerk Maxwell',field:'Fizik',kind:'Bilim',era:'1831–1879'},
    {id:'ahmed-zewail',name:'Ahmed Zewail',trTitle:'Ahmed Zewail',enTitle:'Ahmed Zewail',field:'Kimya',kind:'Bilim',era:'1946–2016'},
    {id:'leonardo-da-vinci',name:'Leonardo da Vinci',trTitle:'Leonardo da Vinci',enTitle:'Leonardo da Vinci',field:'Resim · Tasarım · Gözlem',kind:'Sanat',era:'1452–1519'},
    {id:'michelangelo',name:'Michelangelo',trTitle:'Michelangelo',enTitle:'Michelangelo',field:'Heykel · Resim · Mimarlık',kind:'Sanat',era:'1475–1564'},
    {id:'vincent-van-gogh',name:'Vincent van Gogh',trTitle:'Vincent van Gogh',enTitle:'Vincent van Gogh',field:'Resim',kind:'Sanat',era:'1853–1890'},
    {id:'pablo-picasso',name:'Pablo Picasso',trTitle:'Pablo Picasso',enTitle:'Pablo Picasso',field:'Resim · Heykel',kind:'Sanat',era:'1881–1973'},
    {id:'frida-kahlo',name:'Frida Kahlo',trTitle:'Frida Kahlo',enTitle:'Frida Kahlo',field:'Resim',kind:'Sanat',era:'1907–1954'},
    {id:'rembrandt',name:'Rembrandt',trTitle:'Rembrandt',enTitle:'Rembrandt',field:'Resim · Gravür',kind:'Sanat',era:'1606–1669'},
    {id:'claude-monet',name:'Claude Monet',trTitle:'Claude Monet',enTitle:'Claude Monet',field:'Resim',kind:'Sanat',era:'1840–1926'},
    {id:'georgia-okeeffe',name:'Georgia O’Keeffe',trTitle:"Georgia O'Keeffe",enTitle:"Georgia O'Keeffe",field:'Resim',kind:'Sanat',era:'1887–1986'},
    {id:'yayoi-kusama',name:'Yayoi Kusama',trTitle:'Yayoi Kusama',enTitle:'Yayoi Kusama',field:'Çağdaş sanat',kind:'Sanat',era:'1929–'},
    {id:'artemisia-gentileschi',name:'Artemisia Gentileschi',trTitle:'Artemisia Gentileschi',enTitle:'Artemisia Gentileschi',field:'Resim',kind:'Sanat',era:'1593–yaklaşık 1656'},
    {id:'caravaggio',name:'Caravaggio',trTitle:'Caravaggio',enTitle:'Caravaggio',field:'Resim',kind:'Sanat',era:'1571–1610'},
    {id:'diego-velazquez',name:'Diego Velázquez',trTitle:'Diego Velázquez',enTitle:'Diego Velázquez',field:'Resim',kind:'Sanat',era:'1599–1660'},
    {id:'edvard-munch',name:'Edvard Munch',trTitle:'Edvard Munch',enTitle:'Edvard Munch',field:'Resim · Baskı',kind:'Sanat',era:'1863–1944'},
    {id:'salvador-dali',name:'Salvador Dalí',trTitle:'Salvador Dalí',enTitle:'Salvador Dalí',field:'Resim · Sürrealizm',kind:'Sanat',era:'1904–1989'},
    {id:'henri-matisse',name:'Henri Matisse',trTitle:'Henri Matisse',enTitle:'Henri Matisse',field:'Resim · Kolaj',kind:'Sanat',era:'1869–1954'},
    {id:'gustav-klimt',name:'Gustav Klimt',trTitle:'Gustav Klimt',enTitle:'Gustav Klimt',field:'Resim',kind:'Sanat',era:'1862–1918'},
    {id:'joan-miro',name:'Joan Miró',trTitle:'Joan Miró',enTitle:'Joan Miró',field:'Resim · Heykel',kind:'Sanat',era:'1893–1983'},
    {id:'wassily-kandinsky',name:'Wassily Kandinsky',trTitle:'Wassily Kandinsky',enTitle:'Wassily Kandinsky',field:'Resim · Soyut sanat',kind:'Sanat',era:'1866–1944'},
    {id:'paul-cezanne',name:'Paul Cézanne',trTitle:'Paul Cézanne',enTitle:'Paul Cézanne',field:'Resim',kind:'Sanat',era:'1839–1906'},
    {id:'henri-rousseau',name:'Henri Rousseau',trTitle:'Henri Rousseau',enTitle:'Henri Rousseau',field:'Resim',kind:'Sanat',era:'1844–1910'},
    {id:'osman-hamdi-bey',name:'Osman Hamdi Bey',trTitle:'Osman Hamdi Bey',enTitle:'Osman Hamdi Bey',field:'Resim · Arkeoloji',kind:'Sanat',era:'1842–1910'},
    {id:'ibrahim-calli',name:'İbrahim Çallı',trTitle:'İbrahim Çallı',enTitle:'İbrahim Çallı',field:'Resim',kind:'Sanat',era:'1882–1960'},
    {id:'fikret-mualla',name:'Fikret Muallâ',trTitle:'Fikret Muallâ',enTitle:'Fikret Mualla',field:'Resim',kind:'Sanat',era:'1903–1967'},
    {id:'abidin-dino',name:'Abidin Dino',trTitle:'Abidin Dino',enTitle:'Abidin Dino',field:'Resim · Yazı · Sinema',kind:'Sanat',era:'1913–1993'},
    {id:'bedri-rahmi',name:'Bedri Rahmi Eyüboğlu',trTitle:'Bedri Rahmi Eyüboğlu',enTitle:'Bedri Rahmi Eyüboğlu',field:'Resim · Şiir',kind:'Sanat',era:'1911–1975'},
    {id:'ara-guler',name:'Ara Güler',trTitle:'Ara Güler',enTitle:'Ara Güler',field:'Fotoğraf',kind:'Sanat',era:'1928–2018'},
    {id:'nuri-bilge-ceylan',name:'Nuri Bilge Ceylan',trTitle:'Nuri Bilge Ceylan',enTitle:'Nuri Bilge Ceylan',field:'Sinema · Fotoğraf',kind:'Sanat',era:'1959–'},
    {id:'zeki-muren',name:'Zeki Müren',trTitle:'Zeki Müren',enTitle:'Zeki Müren',field:'Müzik · Sahne sanatları',kind:'Sanat',era:'1931–1996'},
    {id:'asik-veysel',name:'Âşık Veysel',trTitle:'Âşık Veysel',enTitle:'Aşık Veysel',field:'Ozanlık · Müzik',kind:'Sanat',era:'1894–1973'},
    {id:'nazim-hikmet',name:'Nâzım Hikmet',trTitle:'Nâzım Hikmet',enTitle:'Nazım Hikmet',field:'Şiir · Tiyatro',kind:'Sanat',era:'1902–1963'},
    {id:'yasar-kemal',name:'Yaşar Kemal',trTitle:'Yaşar Kemal',enTitle:'Yaşar Kemal',field:'Roman',kind:'Sanat',era:'1923–2015'},
    {id:'orhan-veli',name:'Orhan Veli Kanık',trTitle:'Orhan Veli Kanık',enTitle:'Orhan Veli Kanık',field:'Şiir',kind:'Sanat',era:'1914–1950'},
    {id:'sait-faik',name:'Sait Faik Abasıyanık',trTitle:'Sait Faik Abasıyanık',enTitle:'Sait Faik Abasıyanık',field:'Öykü',kind:'Sanat',era:'1906–1954'},
    {id:'sabahattin-ali',name:'Sabahattin Ali',trTitle:'Sabahattin Ali',enTitle:'Sabahattin Ali',field:'Öykü · Roman · Şiir',kind:'Sanat',era:'1907–1948'},
    {id:'virginia-woolf',name:'Virginia Woolf',trTitle:'Virginia Woolf',enTitle:'Virginia Woolf',field:'Roman · Deneme',kind:'Sanat',era:'1882–1941'},
    {id:'toni-morrison',name:'Toni Morrison',trTitle:'Toni Morrison',enTitle:'Toni Morrison',field:'Roman · Deneme',kind:'Sanat',era:'1931–2019'},
    {id:'maya-angelou',name:'Maya Angelou',trTitle:'Maya Angelou',enTitle:'Maya Angelou',field:'Şiir · Anı · Sahne',kind:'Sanat',era:'1928–2014'},
    {id:'james-baldwin',name:'James Baldwin',trTitle:'James Baldwin',enTitle:'James Baldwin',field:'Roman · Deneme',kind:'Sanat',era:'1924–1987'},
    {id:'gabriel-garcia-marquez',name:'Gabriel García Márquez',trTitle:'Gabriel García Márquez',enTitle:'Gabriel García Márquez',field:'Roman · Gazetecilik',kind:'Sanat',era:'1927–2014'},
    {id:'jorge-luis-borges',name:'Jorge Luis Borges',trTitle:'Jorge Luis Borges',enTitle:'Jorge Luis Borges',field:'Öykü · Şiir · Deneme',kind:'Sanat',era:'1899–1986'},
    {id:'william-shakespeare',name:'William Shakespeare',trTitle:'William Shakespeare',enTitle:'William Shakespeare',field:'Tiyatro · Şiir',kind:'Sanat',era:'1564–1616'},
    {id:'moliere',name:'Molière',trTitle:'Molière',enTitle:'Molière',field:'Tiyatro',kind:'Sanat',era:'1622–1673'},
    {id:'dostoyevsky',name:'Fyodor Dostoyevski',trTitle:'Fyodor Dostoyevski',enTitle:'Fyodor Dostoevsky',field:'Roman · Felsefi edebiyat',kind:'Sanat',era:'1821–1881'},
    {id:'tolstoy',name:'Lev Tolstoy',trTitle:'Lev Tolstoy',enTitle:'Leo Tolstoy',field:'Roman · Düşünce',kind:'Sanat',era:'1828–1910'},
    {id:'simone-de-beauvoir',name:'Simone de Beauvoir',trTitle:'Simone de Beauvoir',enTitle:'Simone de Beauvoir',field:'Felsefe · Edebiyat',kind:'Sanat',era:'1908–1986'},
    {id:'susan-sontag',name:'Susan Sontag',trTitle:'Susan Sontag',enTitle:'Susan Sontag',field:'Deneme · Eleştiri',kind:'Sanat',era:'1933–2004'},
    {id:'akira-kurosawa',name:'Akira Kurosawa',trTitle:'Akira Kurosawa',enTitle:'Akira Kurosawa',field:'Sinema',kind:'Sanat',era:'1910–1998'},
    {id:'satyajit-ray',name:'Satyajit Ray',trTitle:'Satyajit Ray',enTitle:'Satyajit Ray',field:'Sinema · Yazı',kind:'Sanat',era:'1921–1992'},
    {id:'charlie-chaplin',name:'Charlie Chaplin',trTitle:'Charlie Chaplin',enTitle:'Charlie Chaplin',field:'Sinema · Komedi',kind:'Sanat',era:'1889–1977'},
    {id:'beethoven',name:'Ludwig van Beethoven',trTitle:'Ludwig van Beethoven',enTitle:'Ludwig van Beethoven',field:'Bestecilik',kind:'Sanat',era:'1770–1827'}
  ];
})();
