#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=require('../repo-root');
const source=fs.readFileSync(path.join(root,'app/core/saygi.js'),'utf8');
const appSource=fs.readFileSync(path.join(root,'app.js'),'utf8');
const stateSource=fs.readFileSync(path.join(root,'app/core/state.js'),'utf8');
const esc=v=>String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const ids=['bakara-255','ihlas-1','fatiha-5','bakara-286','kehf-10','taha-25','yusuf-87'];
const catalog={catalogVersion:'quran-striking-verses-tr-v2',byId(id){const n=ids.indexOf(id)+1;return {id,surahNameTr:'Sure '+n,ayetNo:String(n),arabic:'آية '+n,transliterationTr:'Okunuş '+n,meal:'Meal '+n,themeTr:'Tema '+n,verified:true};}};
const data={eventLog:{sourceDeviceId:'test-device'},programs:{schemaVersion:1,items:{}}};
const ui={faithTab:'oz'};
const sandbox={console,Date,Math,JSON,Object,Array,String,Number,Boolean,RegExp,Error,Promise,Set,Map,Intl,URL,URLSearchParams,encodeURIComponent,decodeURIComponent,isFinite,isNaN,window:null,self:null,globalThis:null,QuranStrikingVersesV1:catalog};
sandbox.window=sandbox;sandbox.self=sandbox;sandbox.globalThis=sandbox;
vm.runInContext(source,vm.createContext(sandbox),{filename:'saygi.js'});
const r=sandbox.SeymaSaygi;
assert.equal(r.registerSaygi({data:()=>data,ui:()=>ui,getDay:()=>({}),todayStr:()=>'2026-09-22',addDays:(d)=>d,diffDays:()=>0,dayIndexFor:()=>1,dateLabelTR:v=>v,icon:n=>'<i>'+esc(n)+'</i>',esc,featuresLive:()=>true,render:()=>{},quranJourneyHubCardHTML:()=>'',zikrVisible:()=>false,zikrPreviewCardHTML:()=>''}),true);
let html=r.iip21ProgramHTML();
let passed=0;
function test(name,fn){try{fn();passed++;console.log('PASS  '+name);}catch(e){console.error('FAIL  '+name+' — '+e.message);process.exitCode=1;}}
test('başlamamış program dürüst başlangıç kartı üretir',()=>{assert.match(html,/7 GÜNLÜK PİLOT/);assert.match(html,/Yolculuğa başla/);assert.doesNotMatch(html,/Tamamlandı/);});
const started=r.iip21ProgramApply('start');
test('başlatma içerik sürümünü ve yedi kimliği sabitler',()=>{assert.equal(started.status,'active');assert.equal(started.contentVersion,catalog.catalogVersion);assert.deepEqual(Array.from(started.contentIds),ids);});
test('aktif kart ilk durağı, durdur/devam eylemlerini gösterir',()=>{html=r.iip21ProgramHTML();assert.match(html,/1\. GÜN/);assert.match(html,/Bu durağı tamamla/);assert.match(html,/Durdur/);});
const revBefore=started.revision;r.iip21ProgramApply('day:1');
test('tek durak tamamlanır ve çift tamamlama ilerlemeyi çoğaltmaz',()=>{assert.equal(r.iip21ProgramState().completedDays[1]!=null,true);const rev=r.iip21ProgramState().revision;r.iip21ProgramApply('day:1');assert.equal(r.iip21ProgramState().revision,rev);assert.equal(rev>revBefore,true);});
r.iip21ProgramApply('pause');
test('durdur/devam durumu takvim cezası olmadan korunur',()=>{assert.equal(r.iip21ProgramState().status,'paused');html=r.iip21ProgramHTML();assert.match(html,/Devam et/);});
r.iip21ProgramApply('resume');
for(let i=2;i<=7;i++)r.iip21ProgramApply('day:'+i);
test('yedi durak sonrası tamamla ayrı ve açık eylemdir',()=>{const p=r.iip21ProgramState();assert.equal(Object.keys(p.completedDays).length,7);assert.equal(p.status,'active');html=r.iip21ProgramHTML();assert.match(html,/Programı tamamla/);});
r.iip21ProgramApply('finish');
test('tamamlanan program yeniden okumayı ve arşivi açık tutar',()=>{assert.equal(r.iip21ProgramState().status,'completed');html=r.iip21ProgramHTML();assert.match(html,/Yolculuk tamamlandı/);ui.saygiProgramArchive=true;html=r.iip21ProgramHTML();assert.equal((html.match(/iip21-archive-row/g)||[]).length,7);});
catalog.catalogVersion='quran-striking-verses-tr-v3';
test('içerik sürümü değişimi ilerlemeyi silmez',()=>{html=r.iip21ProgramHTML();assert.match(html,/İçerik sürümü değişti/);assert.equal(Object.keys(r.iip21ProgramState().completedDays).length,7);});
test('program state migration ve tek dispatcher kaynakta korunur',()=>{assert.match(stateSource,/iip21-seven-day-pilot/);assert.match(appSource,/program:1/);assert.match(appSource,/iip21ProgramApply/);});
if(process.exitCode)process.exit(1);
console.log(`\nPASS: IIP-21 ${passed}/9`);
