(function(){
  'use strict';

  // MON-23 · Saygı / Öncü / İman domain registry
  // ---------------------------------------------------------------------------
  // İçerik, görünüm ve saf kıble hesapları burada yaşar. Root data rebind'i,
  // App handlerları, modal focus kabuğu dışındaki DOM boyaması ve prayer
  // permission/GPS akışı app.js'te kalır. SaygiPeople ve HijriCalendarV1 her
  // çağrıda çözülür; modül yüklenirken içerik, storage, DOM, timer veya ağ
  // erişimi açılmaz.
  var SAYGI_EPOCH='2026-07-13', SAYGI_CACHE_PREFIX='seyma-saygi-v1:';
  var saygiDeps=null, saygiMemoryCache={}, saygiReadObserver=null;
  var SAYGI_DEPENDENCIES=['data','ui','getDay','todayStr','addDays','diffDays','dayIndexFor','dateLabelTR','icon','esc','featuresLive','render','quranJourneyHubCardHTML','zikrVisible','zikrPreviewCardHTML'];

  function registerSaygi(deps){
    if(saygiDeps||!deps||typeof deps!=='object'||Array.isArray(deps)) return false;
    for(var i=0;i<SAYGI_DEPENDENCIES.length;i++) if(typeof deps[SAYGI_DEPENDENCIES[i]]!=='function') return false;
    saygiDeps=deps;
    return true;
  }
  function dep(name){ return saygiDeps&&typeof saygiDeps[name]==='function'?saygiDeps[name]:null; }
  function stateData(){
    var f=dep('data'); if(f){ try{ return f(); }catch(e){} }
    var st=window.SeymaState; return st?st.data:null;
  }
  function stateUi(){ var f=dep('ui'); if(f){ try{ return f(); }catch(e){} } return null; }
  function dateCall(name,args,fallback){
    var f=dep(name); if(f){ try{ return f.apply(null,args); }catch(e){} }
    var du=window.SeymaDateUtils; if(du&&typeof du[name]==='function') return du[name].apply(du,args);
    return fallback.apply(null,args);
  }
  function todayStr(){ return dateCall('todayStr',[],function(){ var d=new Date(); return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'); }); }
  function addDays(s,n){ return dateCall('addDays',[s,n],function(){ var p=String(s).split('-').map(Number),d=new Date(p[0],p[1]-1,p[2]); d.setDate(d.getDate()+n); return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'); }); }
  function diffDays(a,b){ return dateCall('diffDays',[a,b],function(){ var aa=new Date(String(a)+'T12:00:00'),bb=new Date(String(b)+'T12:00:00'); return Math.round((bb-aa)/86400000); }); }
  function dayIndexFor(date){ return dateCall('dayIndexFor',[date],function(){ return 1; }); }
  function dateLabelTR(date){ return dateCall('dateLabelTR',[date],function(){ return String(date||''); }); }
  function iconHtml(){ var f=dep('icon'); return f?f.apply(null,arguments):''; }
  function escHtml(){ var f=dep('esc'); return f?f.apply(null,arguments):String(arguments[0]==null?'':arguments[0]); }
  function featureLive(){ var f=dep('featuresLive'); return f?!!f():true; }
  function renderCall(){ var f=dep('render'); return f?f.apply(null,arguments):undefined; }
  function quranHub(){ var f=dep('quranJourneyHubCardHTML'); return f?f.apply(null,arguments):''; }
  function zikrVisible(){ var f=dep('zikrVisible'); return f?!!f():true; }
  function zikrPreview(){ var f=dep('zikrPreviewCardHTML'); return f?f.apply(null,arguments):''; }
  function getDayCall(d,date,idx){ var f=dep('getDay'); return f?f(d,date,idx):null; }
  function prayerCall(name,args){
    var p=window.SeymaPrayer, f=dep('prayer:'+name);
    if(f) return f.apply(null,args||[]);
    return p&&typeof p[name]==='function'?p[name].apply(p,args||[]):null;
  }
  function prayerValue(name,fallback){ var p=window.SeymaPrayer; return p&&p[name]!=null?p[name]:fallback; }
  function storageObj(){ var f=dep('storage'); if(f){ try{return f();}catch(e){} } try{return typeof localStorage==='undefined'?null:localStorage;}catch(e){return null;} }
  function fetchFn(){ var f=dep('fetch'); if(f){ try{return f();}catch(e){} } return typeof fetch==='function'?fetch:null; }

  function emptySaygiRoot(){ return {collection:{},streak:0,lastReadDate:''}; }
  function ensureSaygiRoot(){
    var d=stateData(); if(!d) return emptySaygiRoot();
    if(!d.saygi||typeof d.saygi!=='object') d.saygi=emptySaygiRoot();
    if(!d.saygi.collection||typeof d.saygi.collection!=='object') d.saygi.collection={};
    if(typeof d.saygi.streak!=='number'||isNaN(d.saygi.streak)) d.saygi.streak=0;
    if(typeof d.saygi.lastReadDate!=='string') d.saygi.lastReadDate='';
    return d.saygi;
  }
  function emptySaygi(){ return {personId:null,readAt:null,readingEntryId:null}; }
  function ensureSaygiDay(day){
    if(!day||typeof day!=='object') return emptySaygi();
    if(!day.saygi||typeof day.saygi!=='object') day.saygi=emptySaygi();
    if(typeof day.saygi.personId!=='string'&&day.saygi.personId!==null) day.saygi.personId=null;
    if(typeof day.saygi.readAt!=='string'&&day.saygi.readAt!==null) day.saygi.readAt=null;
    if(typeof day.saygi.readingEntryId!=='string'&&day.saygi.readingEntryId!==null) day.saygi.readingEntryId=null;
    return day.saygi;
  }
  function saygiMarkRead(person){
    if(!person) return;
    var root=ensureSaygiRoot(), date=todayStr(), d=stateData(), previousReadDate=root.lastReadDate;
    if(!root.collection[person.id]) root.collection[person.id]={name:person.name||person.id,field:person.field||'',readAt:new Date().toISOString(),favorite:false};
    else root.collection[person.id].readAt=new Date().toISOString();
    var yester=addDays(date,-1), yesterdayRead=false, yDay=d&&d.days&&d.days[yester];
    if(yDay&&yDay.saygi&&yDay.saygi.readAt){ var y=String(yDay.saygi.readAt).slice(0,10); yesterdayRead=(y===yester); }
    root.streak=previousReadDate===date?Math.max(1,root.streak):(yesterdayRead||previousReadDate===yester?root.streak+1:1);
    root.lastReadDate=date;
  }
  function saygiCollection(){ return ensureSaygiRoot().collection; }
  function saygiReadCount(){ return Object.keys(saygiCollection()).length; }
  function saygiStreak(){ return ensureSaygiRoot().streak; }
  function saygiPeople(){ return (window.SaygiPeople&&Array.isArray(window.SaygiPeople))?window.SaygiPeople:[]; }
  function saygiPositiveMod(n,m){ return ((n%m)+m)%m; }
  function saygiPersonForDate(date){ var people=saygiPeople(); if(!people.length) return null; return people[saygiPositiveMod(diffDays(SAYGI_EPOCH,date||todayStr()),people.length)]; }
  function saygiCurrentPerson(){ return saygiPersonForDate(todayStr()); }
  function saygiPersonById(id){ var people=saygiPeople(); for(var i=0;i<people.length;i++) if(people[i].id===id) return people[i]; return null; }
  function saygiModalPerson(){ var u=stateUi()||{}; return (u.saygiPersonOpen&&u.saygiBrowseId?saygiPersonById(u.saygiBrowseId):null)||saygiCurrentPerson(); }
  function saygiDayKey(person,date){ return String(date||todayStr())+'|'+String(person&&person.id||''); }
  function saygiCacheKey(lang,canonical,revision){ return SAYGI_CACHE_PREFIX+String(lang||'tr')+':'+encodeURIComponent(String(canonical||''))+':'+String(revision||'current'); }
  function saygiReadCache(key){
    if(saygiMemoryCache[key]) return saygiMemoryCache[key];
    try{ var s=storageObj(),raw=s&&s.getItem?s.getItem(key):null,val=raw?JSON.parse(raw):null; if(val&&Array.isArray(val.blocks)){ saygiMemoryCache[key]=val; return val; } }catch(e){}
    return null;
  }
  function saygiWriteCache(key,val){ try{ saygiMemoryCache[key]=val; var s=storageObj(); if(s&&s.setItem) s.setItem(key,JSON.stringify(val)); }catch(e){} }
  function saygiSafeUrl(url,hosts){
    try{
      var URLCtor=window.URL||URL,u=new URLCtor(String(url||'')); if(u.protocol!=='https:') return '';
      if(hosts&&hosts.length){ var ok=false; for(var i=0;i<hosts.length;i++) if(u.hostname===hosts[i]||u.hostname.slice(-(hosts[i].length+1))==='.'+hosts[i]){ok=true;break;} if(!ok)return ''; }
      return u.href;
    }catch(e){ return ''; }
  }
  function saygiFetchJSON(url,timeout){
    var fetcher=fetchFn(); if(typeof fetcher!=='function') return Promise.reject(new Error('Tarayıcı ağ isteğini desteklemiyor'));
    var ctrl=(typeof window.AbortController==='function')?new window.AbortController():null,timer=null;
    if(ctrl&&typeof window.setTimeout==='function') timer=window.setTimeout(function(){try{ctrl.abort();}catch(e){}},timeout||18000);
    var opts={headers:{'Accept':'application/json'},credentials:'omit'}; if(ctrl) opts.signal=ctrl.signal;
    function clear(){ if(timer&&typeof window.clearTimeout==='function') window.clearTimeout(timer); }
    return fetcher(url,opts).then(function(res){clear();if(!res.ok){var e=new Error('Wikipedia yanıtı '+res.status);e.status=res.status;return Promise.reject(e);}return res.json();},function(err){clear();return Promise.reject(err);});
  }
  function saygiSummaryUrl(lang,title){ return 'https://'+lang+'.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(String(title||'').replace(/ /g,'_')); }
  function saygiHtmlUrl(lang,title){ return 'https://'+lang+'.wikipedia.org/w/rest.php/v1/page/'+encodeURIComponent(String(title||'').replace(/ /g,'_'))+'/with_html'; }
  function saygiFetchSummary(lang,title){ return saygiFetchJSON(saygiSummaryUrl(lang,title)).then(function(j){if(!j||j.type==='disambiguation'||j.type==='no-extract'||!j.title)return Promise.reject(new Error('Uygun Wikipedia maddesi bulunamadı'));j._saygiLang=lang;j._saygiRequestedTitle=title;return j;}); }
  function saygiLoadSummary(person){ return saygiFetchSummary('tr',person.trTitle||person.name).catch(function(){return saygiFetchSummary('en',person.enTitle||person.name);}); }
  function saygiPlainText(value){ return String(value==null?'':value).replace(/\[[^\]]{1,80}\]/g,' ').replace(/\s+/g,' ').trim(); }
  function saygiStopHeading(text){ return /^(kaynakça|kaynaklar|notlar|dipnotlar|dış bağlantılar|ayrıca bakınız|bibliyografya|referanslar|further reading|references|external links|notes)$/i.test(saygiPlainText(text)); }
  function saygiBioBlocks(html){
    var Parser=window.DOMParser; if(!html||typeof Parser!=='function') return [];
    var doc,root; try{doc=new Parser().parseFromString(String(html),'text/html');root=doc.querySelector('.mw-parser-output')||doc.body;}catch(e){return [];} if(!root)return [];
    var remove=root.querySelectorAll('script,style,table,figure,figcaption,aside,nav,sup,.reference,.reflist,.mw-editsection,.infobox,.navbox,.vertical-navbox,.metadata,.noprint,.hatnote,.thumb,.toc,.mw-empty-elt'); for(var r=0;r<remove.length;r++)remove[r].remove();
    var nodes=root.querySelectorAll('h2,h3,p,ul,ol'),out=[],chars=0,headings=0;
    for(var i=0;i<nodes.length;i++){
      var node=nodes[i],tag=String(node.tagName||'').toLowerCase(),text='';
      if(tag==='ul'||tag==='ol'){var lis;try{lis=node.querySelectorAll(':scope > li');}catch(e){lis=node.children||[];}if(!lis.length)lis=node.querySelectorAll('li');var items=[];for(var li=0;li<lis.length&&items.length<5;li++){var item=saygiPlainText(lis[li].textContent);if(item.length>16)items.push(item);}text=items.join(' · ');}else text=saygiPlainText(node.textContent);
      if(!text)continue; if(tag==='h2'||tag==='h3'){if(saygiStopHeading(text))break;if(text.length<3||headings>=5)continue;headings++;out.push({type:'h',text:text});continue;}
      if(text.length<(tag==='p'?70:38))continue; if(chars+text.length>8200)text=text.slice(0,Math.max(0,8200-chars)).replace(/\s+\S*$/,'')+'…'; if(text.length<24)break; out.push({type:tag==='p'?'p':'list',text:text}); chars+=text.length; if(out.length>=15||chars>=8200)break;
    }
    return out;
  }
  function saygiExternalLinks(lang,title){
    var Params=window.URLSearchParams||URLSearchParams,p=new Params({action:'query',format:'json',formatversion:'2',origin:'*',prop:'extlinks',ellimit:'8',titles:String(title||'')});
    return saygiFetchJSON('https://'+lang+'.wikipedia.org/w/api.php?'+p.toString(),14000).then(function(j){var pages=j&&j.query&&j.query.pages,page=Array.isArray(pages)?pages[0]:null,list=page&&Array.isArray(page.extlinks)?page.extlinks:[],seen={},out=[];for(var i=0;i<list.length&&out.length<3;i++){var raw=list[i]&&(list[i]['*']||list[i].url||list[i]),safe=saygiSafeUrl(raw);if(!safe||seen[safe])continue;try{var URLCtor=window.URL||URL,host=new URLCtor(safe).hostname.replace(/^www\./,'');if(/(?:wikipedia|wikimedia)\.org$/i.test(host))continue;seen[safe]=true;out.push({url:safe,host:host});}catch(e){}}return out;}).catch(function(){return [];});
  }
  function saygiArticleFrom(person,summary,full,links){
    var lang=summary._saygiLang||'tr',canonical=(summary.titles&&summary.titles.canonical)||summary.title||summary._saygiRequestedTitle||person.name,blocks=saygiBioBlocks(full&&full.html); if(!blocks.length&&summary.extract)blocks=[{type:'p',text:saygiPlainText(summary.extract)}];
    var thumbnail=saygiSafeUrl(summary.thumbnail&&summary.thumbnail.source,['upload.wikimedia.org']),source=saygiSafeUrl(summary.content_urls&&summary.content_urls.desktop&&summary.content_urls.desktop.page,[lang+'.wikipedia.org'])||('https://'+lang+'.wikipedia.org/wiki/'+encodeURIComponent(canonical)),license=(full&&full.license)||{},licenseUrl=saygiSafeUrl(license.url)||'https://creativecommons.org/licenses/by-sa/4.0/deed.tr';
    return {personId:person.id,dailyKey:saygiDayKey(person),lang:lang,title:String(summary.title||person.name),canonical:String(canonical),description:saygiPlainText(summary.description||person.field||''),lead:saygiPlainText(summary.extract||''),blocks:blocks,thumbnail:thumbnail,sourceUrl:source,licenseTitle:String(license.title||'Creative Commons Attribution-Share Alike 4.0'),licenseUrl:licenseUrl,revision:(full&&full.latest&&full.latest.id)||summary.revision||null,links:links||[],fetchedAt:new Date().toISOString()};
  }
  function saygiArticleReadableFor(person,article,date){ if(!person||!article||typeof article!=='object'||article.personId!==person.id||article.dailyKey!==saygiDayKey(person,date||todayStr()))return false;if(!Array.isArray(article.blocks)||!article.blocks.length)return false;return article.blocks.some(function(block){return block&&typeof block.text==='string'&&block.text.trim().length>=24;}); }
  function saygiRequestIsCurrent(person,dailyKey,requestId){ var u=stateUi()||{};if(requestId!==u.saygiRequestId||dailyKey!==saygiDayKey(person))return false;return !u.saygiPersonOpen||String(u.saygiBrowseId||'')===String(person.id); }
  function saygiLoadArticle(person,force){
    if(!person)return; var u=stateUi(); if(!u)return; var dailyKey=saygiDayKey(person),requestId=(u.saygiRequestId||0)+1; u.saygiRequestId=requestId;u.saygiLoading=true;u.saygiError=null;u.saygiReadReady=false;if(force||!u.saygiArticle||u.saygiArticle.personId!==person.id)u.saygiArticle=null;
    saygiLoadSummary(person).then(function(summary){var canonical=(summary.titles&&summary.titles.canonical)||summary.title||person.name,lang=summary._saygiLang||'tr',cacheKey=saygiCacheKey(lang,canonical,summary.revision||'current'),cached=!force?saygiReadCache(cacheKey):null;if(cached&&saygiArticleReadableFor(person,cached))return cached;return saygiFetchJSON(saygiHtmlUrl(lang,canonical),20000).catch(function(){return null;}).then(function(full){return saygiExternalLinks(lang,canonical).then(function(links){var article=saygiArticleFrom(person,summary,full,links);if(!saygiArticleReadableFor(person,article))throw new Error('Wikipedia maddesi okunabilir içerik taşımıyor');saygiWriteCache(cacheKey,article);return article;});});}).then(function(article){if(!saygiRequestIsCurrent(person,dailyKey,requestId))return;u.saygiArticle=article;u.saygiLoading=false;u.saygiError=null;if(u.tab==='saygi')renderCall();}).catch(function(){if(!saygiRequestIsCurrent(person,dailyKey,requestId))return;u.saygiLoading=false;u.saygiError='Biyografi şu an yüklenemedi. Bağlantını kontrol edip yeniden deneyebilirsin.';if(u.tab==='saygi')renderCall();});
  }
  function saygiEnsureArticle(person){ var u=stateUi();if(!u)return;var key=saygiDayKey(person);if(u.saygiKey!==key){u.saygiKey=key;u.saygiArticle=null;u.saygiLoading=false;u.saygiError=null;u.saygiReadReady=false;}if(!u.saygiArticle&&!u.saygiLoading)saygiLoadArticle(person,false); }
  function saygiReadMinutes(article){ var text=(article&&article.blocks||[]).map(function(b){return b.text;}).join(' ');return Math.max(4,Math.min(18,Math.round(text.length/850)||4)); }
  function saygiReadingEntry(day,person){ var entries=day&&day.reading&&Array.isArray(day.reading.entries)?day.reading.entries:[];for(var i=0;i<entries.length;i++){var e=entries[i];if(e&&e.source==='saygi'&&e.personId===person.id&&e.saygiDate===todayStr())return e;}return null; }
  function saygiHasRead(person){ var d=stateData(),day=d&&d.days&&d.days[todayStr()];if(!day||!person)return false;var entry=saygiReadingEntry(day,person);if(!entry)return false;var st=ensureSaygiDay(day);if(st.readingEntryId!==entry.id){st.personId=person.id;st.readingEntryId=entry.id;st.readAt=entry.ts||st.readAt||new Date().toISOString();}return true; }
  function saygiDomainTone(host){ var colors=['#735F37','#4B6670','#76536A','#526753','#6B5B86','#8B6047'],n=0,s=String(host||'');for(var i=0;i<s.length;i++)n=(n*31+s.charCodeAt(i))>>>0;return colors[n%colors.length]; }

  function faithWeekKPIs(date){
    date=date||todayStr();var d=stateData()||{},days=d.days||{},order=prayerValue('PRAYER_ORDER',[]),prays=0,cong=0,made=0,late=0,nafile=0,dayCount=0;
    for(var i=0;i<7;i++){var key=addDays(date,-i),rec=days[key];if(!rec||!rec.prayer)continue;dayCount++;order.forEach(function(k){var e=rec.prayer[k];if(!e)return;if(e.performed){prays++;if(e.inCongregation)cong++;if(e.late)late++;if(e.madeUp)made++;}nafile+=Math.max(0,Number(e.nafile)||0);});}
    var z=zikrCall('zikrWeek',[date])||{total:0,days:0};return {prays:prays,maxPrays:dayCount*6,cong:cong,madeUp:made,late:late,nafile:nafile,zikrTotal:z.total,zikrDays:z.days};
  }
  function faithDayHeat(date){ var d=stateData()||{},rec=d.days&&d.days[date],order=prayerValue('PRAYER_ORDER',[]),performed=0;if(rec&&rec.prayer)order.forEach(function(k){if(rec.prayer[k]&&rec.prayer[k].performed)performed++;});var z=d.zikr&&d.zikr.sessions&&d.zikr.sessions[date],sets=z&&Number(z.completedSets)||0,total=z&&Number(z.totalCount)||0,level=performed===0?0:(performed<=2?1:(performed<=4?2:3));if(sets>0||total>0)level=Math.min(4,Math.max(1,level+1));return {performed:performed,zikr:total,sets:sets,level:level}; }
  function zikrCall(name,args){ var z=window.SeymaZikr,f=dep('zikr:'+name);if(f)return f.apply(null,args||[]);return z&&typeof z[name]==='function'?z[name].apply(z,args||[]):null; }
  function qiblaBearing(lat,lon){var kl=21.4225*Math.PI/180,kn=39.8262*Math.PI/180,la=lat*Math.PI/180,lo=lon*Math.PI/180,y=Math.sin(kn-lo)*Math.cos(kl),x=Math.cos(la)*Math.sin(kl)-Math.sin(la)*Math.cos(kl)*Math.cos(kn-lo),br=Math.atan2(y,x)*180/Math.PI;return Math.round(((br+360)%360)*10)/10;}
  function qiblaDistanceKm(lat,lon){var r=6371.0088,la=lat*Math.PI/180,lo=lon*Math.PI/180,kl=21.4225*Math.PI/180,kn=39.8262*Math.PI/180,dlat=kl-la,dlon=kn-lo,a=Math.sin(dlat/2)*Math.sin(dlat/2)+Math.cos(la)*Math.cos(kl)*Math.sin(dlon/2)*Math.sin(dlon/2);return Math.round(r*2*Math.atan2(Math.sqrt(a),Math.sqrt(Math.max(0,1-a))));}
  function qiblaDirectionLabel(bearing){var labels=['kuzey','kuzey-kuzeydoğu','kuzeydoğu','doğu-kuzeydoğu','doğu','doğu-güneydoğu','güneydoğu','güney-güneydoğu','güney','güney-güneybatı','güneybatı','batı-güneybatı','batı','batı-kuzeybatı','kuzeybatı','kuzey-kuzeybatı'];return labels[Math.round((((Number(bearing)||0)%360)+360)%360/22.5)%16];}
  function qiblaMetrics(location,heading){var valid=location&&isFinite(+location.lat)&&isFinite(+location.lon),loc=valid?location:{lat:39.9334,lon:32.8597,cityName:'Ankara',source:'fallback'},bearing=qiblaBearing(+loc.lat,+loc.lon),distance=qiblaDistanceKm(+loc.lat,+loc.lon),hasHeading=heading!==null&&heading!==''&&isFinite(Number(heading)),hd=hasHeading?(((Number(heading)%360)+360)%360):0,relative=((bearing-hd)%360+360)%360,error=hasHeading?Math.abs(((bearing-hd+540)%360)-180):null;return {bearing:bearing,distanceKm:distance,direction:qiblaDirectionLabel(bearing),relative:relative,alignmentError:error,hasHeading:hasHeading,location:loc,isFallback:!valid};}
  function qiblaLocationPrecision(m){var loc=m.location||{},acc=Number(loc.accuracy);if(m.isFallback)return 'Geçici Ankara merkezi';if(loc.source==='gps'&&isFinite(acc)&&acc>0)return 'GPS ±'+Math.round(acc)+' m';if(loc.source==='gps')return 'GPS konumu';return 'Şehir merkezi hesabı';}
  function qiblaAlignmentCopy(m){if(!m.hasHeading)return {state:'idle',title:'Canlı yön bekleniyor',detail:'Sensör izni verince telefonun üst kenarını Kâbe doğrultusuna hizala.'};var e=Math.round(m.alignmentError*10)/10,signed=((m.relative+540)%360)-180,turn=signed>=0?'sağa':'sola';if(e<=3)return {state:'aligned',title:'Kıbleye hizalandın',detail:'Sensör farkı '+e.toLocaleString('tr-TR')+'°'};if(e<=12)return {state:'near',title:'Çok yakınsın',detail:e.toLocaleString('tr-TR')+'° '+turn+' çevir'};return {state:'seeking',title:'Telefonu '+turn+' çevir',detail:e.toLocaleString('tr-TR')+'° yön farkı'};}
  function qiblaScreenAngle(){var angle=0;try{if(window.screen&&window.screen.orientation&&isFinite(Number(window.screen.orientation.angle)))angle=Number(window.screen.orientation.angle);else if(isFinite(Number(window.orientation)))angle=Number(window.orientation);}catch(e){}return ((angle%360)+360)%360;}

  function saygiSourceFallback(person){return 'https://tr.wikipedia.org/wiki/'+encodeURIComponent(String(person&&person.trTitle||person&&person.name||'').replace(/ /g,'_'));}
  function saygiSourceCardHTML(article,link,isWiki){var href=isWiki?saygiSafeUrl(article.sourceUrl):saygiSafeUrl(link&&link.url),host=isWiki?(article.lang==='tr'?'tr.wikipedia.org':'en.wikipedia.org'):String(link&&link.host||''),tone=isWiki?'#7A5E2D':saygiDomainTone(host),label=isWiki?(article.lang==='tr'?'Wikipedia · Türkçe kaynak':'Wikipedia · English source'):host;if(!href)return '';var thumb=isWiki&&article.thumbnail?'<img src="'+escHtml(article.thumbnail)+'" alt="" loading="lazy" referrerpolicy="no-referrer">':'<span class="saygi-link-monogram">'+escHtml((host||'K').charAt(0).toUpperCase())+'</span>';return '<a class="saygi-source-card'+(isWiki?' is-wikipedia':'')+'" href="'+escHtml(href)+'" target="_blank" rel="noopener noreferrer" style="--saygi-link-tone:'+tone+';"><span class="saygi-link-thumb">'+thumb+'</span><span class="saygi-link-copy"><span class="saygi-link-label">'+escHtml(label)+'</span><span class="saygi-link-sub">'+(isWiki?'Maddesini ve kaynaklarını aç':'Kaynakta geçen dış bağlantı')+'</span></span><span class="saygi-link-arrow">'+iconHtml('external-link',14)+'</span></a>';}
  function saygiReadActionHTML(done,suffix,disabled,main,sub){suffix=suffix||'';var u=stateUi()||{},ready=!!u.saygiReadReady;if(main==null){disabled=!done&&!ready;main=done?'Okudum':(ready?'Okudum':'Okudum kilitli');sub=done?'Ne okudum kaydını aç':(ready?'Bugünün kaydına ekle':'Yazının sonuna inince açılır');}return '<div class="saygi-finish-card"><div class="saygi-finish-orbit">'+iconHtml(done?'circle-check':'book-open',22)+'</div><div class="saygi-finish-copy"><div>Bugünün düşüncesi burada tamamlandı.</div><small>Bu biyografiyi okuduysan kaydını bugüne ekleyelim.</small></div></div><button id="saygi-read-button'+suffix+'" class="saygi-read-button'+(done?' is-done':(ready?' is-ready':' is-locked'))+'" '+(disabled?'disabled':'')+' onclick="'+(done?'App.openSaygiReading()':'App.markSaygiRead()')+'"><span class="saygi-read-button-icon">'+iconHtml(done?'circle-check':'book-open',19)+'</span><span><strong data-saygi-read-copy>'+main+'</strong><small data-saygi-read-sub>'+sub+'</small></span></button>';}
  function saygiReadButtonHTML(person,done,suffix){suffix=suffix||'';var u=stateUi()||{},ready=!!u.saygiReadReady,disabled=!done&&!ready,main=done?'Okudum':(ready?'Okudum':'Okudum kilitli'),sub=done?'Ne okudum kaydını aç':(ready?'Bugünün kaydına ekle':'Yazının sonuna inince açılır');return '<div id="saygi-read-sentinel'+suffix+'" class="saygi-read-sentinel" aria-hidden="true"></div>'+saygiReadActionHTML(done,suffix,disabled,main,sub);}
  function saygiLoadingHTML(){return '<div class="saygi-loading" role="status"><div class="saygi-loading-mark">'+iconHtml('trophy',26)+'</div><div><strong>Bugünün biyografisi hazırlanıyor</strong><span>Wikipedia’dan metin, görsel ve kaynaklar güvenli biçimde alınıyor.</span></div><div class="saygi-loading-lines"><i></i><i></i><i></i></div></div>';}
  function saygiComingSoonHTML(){var h='<section class="saygi-page"><div class="saygi-intro"><div><div class="saygi-kicker">'+iconHtml('trophy',13)+' SAYGI · GÜNÜN İSMİ</div><h1>Bir hayat, bir iz.</h1><p>Bilimin ve sanatın yönünü değiştiren 100 kişiden her gün biri. Hızlıca geçmek için değil, biraz durup anlamak için.</p></div></div><div class="saygi-loading"><span class="saygi-loading-mark">'+iconHtml('clock',20)+'</span><div><strong>Yakında açılıyor</strong><span>Saygı, 13 Temmuz sabahı ilk isimle başlıyor. O güne kadar burada bekliyor olacak.</span></div></div></section>';return h;}
  function faithSummaryBadges(p,compact){var s=prayerCall('prayerDaySummary',[p])||{},badges=[];badges.push('<span class="sg-faith-badge '+(s.performed>=5?'ok':'')+'">'+s.performed+'/'+(compact?6:s.total)+' vakit</span>');if(s.congregation)badges.push('<span class="sg-faith-badge">'+s.congregation+' cemaat</span>');if(s.madeUp)badges.push('<span class="sg-faith-badge warn">'+s.madeUp+' kaza</span>');return badges.join('');}
  function faithCornerCardHTML(){var date=todayStr(),d=stateData()||{},day=getDayCall(d,date,dayIndexFor(date))||{},p=prayerCall('ensurePrayerDay',[day])||{},loc=prayerCall('prayerLocation',[])||{},s=prayerCall('prayerDaySummary',[p])||{},streak=prayerCall('prayerStreak',[])||0,times=prayerCall('prayerTimesFromDay',[p])||{},order=prayerValue('PRAYER_ORDER',[]),curIdx=prayerCall('currentPrayerIndex',[times])||0,nextIdx=(curIdx+1<order.length?curIdx+1:order.length-1),locName=loc&&loc.cityName?escHtml(loc.cityName):(loc?'Konum ayarlandı':'Konum seçilmedi'),nx=prayerCall('nextPrayerInfo',[times])||{},pct=Math.round((s.performed/6)*100),allDone=s.performed>=6,nextKey=nx.key||order[nextIdx]||order[0],nextEntry=p[nextKey]||prayerCall('emptyPrayerEntry',[])||{};var h='<button id="faith-preview-card" class="hub-v2-preview faith-v2-preview'+(allDone?' is-complete':'')+'" onclick="App.openFaithCorner()" aria-label="İman Köşesini aç"><div class="hub-v2-preview-top"><span class="hub-v2-preview-icon">'+iconHtml('mosque',20)+'</span><div class="hub-v2-preview-copy"><strong>İman Köşesi</strong><small>'+locName+' · '+dateLabelTR(date)+'</small></div><span class="hub-v2-preview-status '+(allDone?'complete':'active')+'">'+(allDone?'tamamlandı':s.performed+'/6 vakit')+'</span></div><div class="hub-v2-preview-focus"><div><span class="eyebrow">SIRADAKİ VAKİT</span><strong>'+escHtml(nx.name||prayerValue('PRAYER_NAMES',{})[nextKey]||'Vakit')+'</strong><p>'+(nx.label?escHtml(nx.label):'Vakit bilgisi hazırlanıyor')+'</p></div><span class="faith-time">'+escHtml(nextEntry.time||'--:--')+'</span></div><div class="hub-v2-preview-metric"><div><span>Kılınan</span><strong>'+s.performed+' / 6</strong><small>bugün</small></div><div><span>Cemaat</span><strong>'+s.congregation+'</strong><small>vakit</small></div><div><span>Devamlılık</span><strong>'+streak+'</strong><small>gün seri</small></div></div><div class="hub-v2-preview-bar" aria-label="'+s.performed+' / 6 vakit tamamlandı"><i style="width:'+pct+'%"></i></div><div class="hub-v2-preview-foot"><span>'+(s.madeUp?iconHtml('rotate-ccw',12)+s.madeUp+' kaza':'Bugünün ibadet ritmi')+'</span><b>Vakitleri aç '+iconHtml('chevron-right',13)+'</b></div></button>';return h;}
  function saygiPreviewCardHTML(person,done,article){if(!person)return '';var thumb=article&&article.thumbnail?'<img src="'+escHtml(article.thumbnail)+'" alt="" loading="lazy" referrerpolicy="no-referrer">':'<span class="sg-person-preview-thumb-fallback">'+escHtml((person.name||'?').charAt(0).toUpperCase())+'</span>',readCount=saygiReadCount(),pct=Math.min(100,Math.round((readCount/100)*100));var h='<button id="saygi-preview-card" class="hub-v2-preview person-v2-preview'+(done?' is-complete':'')+'" onclick="App.openSaygiPreview()" aria-label="Günün öncüsü: '+escHtml(person.name)+'"><div class="hub-v2-preview-top"><span class="hub-v2-preview-icon">'+iconHtml('trophy',20)+'</span><div class="hub-v2-preview-copy"><strong>Günün Öncüsü</strong><small>100 hayat · 100 iz</small></div><span class="hub-v2-preview-status '+(done?'complete':'active')+'">'+(done?'okundu':'bugün keşfet')+'</span></div><div class="hub-v2-preview-focus"><div><span class="eyebrow">'+escHtml(person.kind)+' · '+escHtml(person.era)+'</span><strong>'+escHtml(person.name)+'</strong><p>'+(article&&article.description?escHtml(article.description):escHtml(person.field))+'</p></div><span class="person-thumb">'+thumb+'</span></div><div class="hub-v2-preview-metric"><div><span>Alan</span><strong>'+escHtml(person.kind)+'</strong><small>'+escHtml(person.field)+'</small></div><div><span>Okuma</span><strong>'+(article?saygiReadMinutes(article):2)+' dk</strong><small>'+(article&&article.lang==='tr'?'Türkçe':'Wikipedia')+'</small></div><div><span>Koleksiyon</span><strong>'+readCount+' / 100</strong><small>'+saygiStreak()+' gün seri</small></div></div><div class="hub-v2-preview-bar" aria-label="100 öncüden '+readCount+' okundu"><i style="width:'+pct+'%"></i></div><div class="hub-v2-preview-foot"><span>'+iconHtml(person.kind==='Bilim'?'microscope':'feather',12)+escHtml(person.field)+'</span><b>'+(done?'Yeniden oku':'Biyografiyi aç')+' '+iconHtml('chevron-right',13)+'</b></div></button>';return h;}
  function saygiMissionCardHTML(){return '<div class="sg-mission-card"><div class="sg-mission-kicker">'+iconHtml('trophy',12)+' İLHAM · GÜNÜN İSMİ</div><h2 class="sg-mission-title">Bir hayat, bir iz.</h2><p class="sg-mission-desc">Bilimin ve sanatın yönünü değiştiren 100 kişiden her gün biri. Hızlıca geçmek için değil, biraz durup anlamak için.</p></div>';}
  function faithCornerInlineHTML(){return faithCornerCardHTML();}
  function prayerRowHTML(type,entry,isCurrent,isNext){var names=prayerValue('PRAYER_NAMES',{}),name=names[type]||type,performed=!!entry.performed,cong=!!entry.inCongregation,late=!!entry.late,madeUp=!!entry.madeUp,nafile=Math.max(0,Number(entry.nafile)||0),cls='sg-faith-row'+(isCurrent?' current':'');var h='<div class="'+cls+'"><div class="sg-faith-row-name">'+escHtml(name)+'</div><div class="sg-faith-row-time">'+(entry.time?escHtml(entry.time):'--:--')+'</div><div class="sg-faith-row-status" style="flex-wrap:wrap;gap:6px;"><button class="sg-faith-chip '+(performed?'on':'')+'" onclick="App.togglePrayer(\''+type+'\',\'performed\')">'+(performed?iconHtml('check',12):'')+' Kılındı</button><button class="sg-faith-chip '+(cong?'on':'')+'" onclick="App.togglePrayer(\''+type+'\',\'inCongregation\')">'+(cong?iconHtml('users',12):'')+' Cemaat</button><button class="sg-faith-chip '+(late?'warn':'')+'" onclick="App.togglePrayer(\''+type+'\',\'late\')">'+(late?iconHtml('clock',12):'')+' Geç</button><button class="sg-faith-chip '+(madeUp?'warn':'')+'" onclick="App.togglePrayer(\''+type+'\',\'madeUp\')">'+(madeUp?iconHtml('refresh-ccw',12):'')+' Kaza</button></div><div class="sg-faith-nafile"><button onclick="App.changeNafile(\''+type+'\',-1)">−</button><span>'+nafile+'</span><button onclick="App.changeNafile(\''+type+'\',1)">+</button></div></div><textarea class="sg-faith-note" rows="1" placeholder="'+escHtml(name)+' notu…" oninput="App.setPrayerNote(\''+type+'\',this)">'+(entry.note?escHtml(entry.note):'')+'</textarea>';return h;}
  function hijriTodayStr(){var c=window.HijriCalendarV1,ps=prayerCall('prayerSettings',[])||{};if(c&&c.todayStr)return c.todayStr(todayStr(),ps.hijriOffset||0);var d=new Date(),mo=['Muharrem','Safer','Rebiülevvel','Rebiülâhir','Cemaziyelevvel','Cemaziyelâhir','Receb','Şaban','Ramazan','Şevval','Zilkade','Zilhicce'];return mo[d.getMonth()]?mo[d.getMonth()]+' '+d.getDate():'';}
  function kandilBadgeFor(date){var c=window.HijriCalendarV1;return c&&c.holyDay?c.holyDay(date)||'':'';}
  function spiritBarHTML(){var date=todayStr(),d=stateData()||{},day=getDayCall(d,date,dayIndexFor(date))||{},p=prayerCall('ensurePrayerDay',[day])||{},times=prayerCall('prayerTimesFromDay',[p])||{},nx=prayerCall('nextPrayerInfo',[times])||{},h='<div class="sg-spirit-bar sg-glass"><span class="nnext">'+iconHtml('mosque',13)+' '+escHtml(nx.name)+(nx.label?' · <strong>'+escHtml(nx.label)+'</strong>':'')+'</span><span class="dot">·</span><span class="hijri">🌙 '+escHtml(hijriTodayStr())+'</span>';var kand=kandilBadgeFor(date);if(kand)h+='<span class="kandil">'+iconHtml('sparkles',11)+' '+escHtml(kand)+'</span>';return h+'</div>';}
function faithCornerOverlayHTML(){
  var date=todayStr(), d=stateData()||{}, day=getDayCall(d,date,dayIndexFor(date));
  var p=prayerCall('ensurePrayerDay',[day])||{}, loc=prayerCall('prayerLocation',[])||{}, times=prayerCall('prayerTimesFromDay',[p])||{};
  var curIdx=prayerCall('currentPrayerIndex',[times])||0, nextIdx=(curIdx+1<prayerValue('PRAYER_ORDER',[]).length?curIdx+1:prayerValue('PRAYER_ORDER',[]).length-1);
  var s=prayerCall('prayerDaySummary',[p])||{}, streak=prayerCall('prayerStreak',[])||0;
  var head='<div style="display:flex;justify-content:space-between;align-items:flex-start;gap:10px;"><div><div style="font-size:var(--f-title3);font-weight:800;display:flex;align-items:center;gap:8px;">İman Köşesi '+iconHtml('mosque',19)+'</div><div style="font-size:var(--f-footnote);color:var(--faint);margin-top:3px;">Bugünün vakitleri, kılındı/cemaat/kaza/geç/nafile takibi.</div></div><button onclick="App.closeFaithCorner()" style="border:none;background:color-mix(in srgb,var(--faith) 16%, transparent);cursor:pointer;width:34px;height:34px;border-radius:50%;color:var(--muted);flex-shrink:0;display:flex;align-items:center;justify-content:center;">'+iconHtml('x',16)+'</button></div>';
  var body='';
  // Faz 36 — Sonraki vakit geri sayım
  var nx=prayerCall('nextPrayerInfo',[times])||{};
  if(nx.key){ var remPct=nx.remMin!=null?Math.max(0,Math.min(100,100-Math.round(nx.remMin/(1440/100)))):0;
    body+='<div class="sg-faith-next"><div class="nm">'+iconHtml('clock',14)+' Sonraki: '+escHtml(nx.name)+'</div><div class="cd">'+escHtml(nx.label)+'</div></div>';
    body+='<div class="sg-faith-next-bar"><i style="width:'+remPct+'%;"></i></div>';
  }
  // Konum / şehir seçimi
  body+='<div class="sg-faith-city">'+iconHtml('map-pin',14)+'<select onchange="App.setPrayerCity(this.value)">'+(prayerCall('prayerCityOptionsHTML',[loc&&loc.cityName])||'')+'</select><button onclick="App.fetchPrayerLocationGPS()" style="border:none;background:transparent;cursor:pointer;color:var(--faith);display:inline-flex;align-items:center;justify-content:center;width:26px;height:26px;border-radius:50%;">'+iconHtml('compass',14)+'</button></div>';
  // Günlük özet — hicri + mübarek rozet (Faz 37)
  var hijri=hijriTodayStr(), kand=kandilBadgeFor(date), hoff=Number((prayerCall('prayerSettings',[])||{}).hijriOffset)||0;
  body+='<div class="sg-hijri-row"><span>🌙 '+escHtml(hijri)+(hoff?' · '+(hoff>0?'+':'')+hoff+' gün':'')+'</span>'+(kand?'<span class="kandil">'+iconHtml('sparkles',10)+' '+escHtml(kand)+'</span>':'')+'<span class="sg-hijri-adjust"><button onclick="App.adjustHijriOffset(-1)" '+(hoff<=-2?'disabled':'')+' aria-label="Hicri tarihi bir gün geri al">−</button><button onclick="App.adjustHijriOffset(1)" '+(hoff>=2?'disabled':'')+' aria-label="Hicri tarihi bir gün ileri al">+</button></span></div>';
  body+='<div class="sg-faith-summary"><strong>'+s.performed+'/6 vakit</strong><span>· '+s.congregation+' cemaat · '+s.madeUp+' kaza · '+s.late+' geç · '+s.nafile+' nafile</span>'+(streak?'<span style="margin-left:auto;font-weight:800;color:var(--faith);">'+streak+' gün seri</span>':'')+'</div>';
  // Vakit satırları
  body+='<div style="display:flex;flex-direction:column;gap:6px;">';
  prayerValue('PRAYER_ORDER',[]).forEach(function(k,i){ body+=prayerRowHTML(k, p[k]||(prayerCall('emptyPrayerEntry',[])||{}), i===curIdx, i===nextIdx); });
  body+='</div>';
  // Yardımcı not
  body+='<div style="border-radius:12px;padding:11px 12px;background:var(--faith-bg);border:1px solid color-mix(in srgb,var(--faith) 18%, var(--card-bd));font-size:var(--f-caption1);line-height:1.45;color:var(--text2);">';
  body+=iconHtml('sparkles',13)+' Vakitler Aladhan API ile Diyanet (method 13) hesabına göre çekilir. Şehir değişince otomatik yenilenir; offline son cache kullanılır.';
  body+='</div>';
  return '<div id="sey-ov-back" class="sey-faith-ov-back sg-faith-ov-back" onclick="App.closeFaithCorner()" style="position:fixed;inset:0;z-index:340;background:rgba(44,36,38,0.42);display:flex;align-items:flex-end;justify-content:center;padding:14px;"><div id="sey-ov-card" class="sey-faith-ov-card sg-faith-ov-card" role="dialog" aria-modal="true" aria-label="İman köşesi" tabindex="-1" onkeydown="App.onModalKeydown(event,App.closeFaithCorner)" onclick="event.stopPropagation()" style="width:100%;max-width:460px;max-height:88vh;background:var(--modal);border-radius:26px;padding:20px;box-shadow:0 -10px 40px rgba(0,0,0,0.22);display:flex;flex-direction:column;gap:13px;overflow:hidden;"><div style="flex-shrink:0;display:flex;flex-direction:column;gap:13px;">'+head+'</div><div id="sey-ov-body" class="scroll" style="flex:1;min-height:0;overflow-y:auto;display:flex;flex-direction:column;gap:14px;margin:0 -4px;padding:4px 4px 2px;">'+body+'</div></div></div>';
}
  function saygiCollectionCardHTML(person){var coll=saygiCollection(),read=saygiReadCount(),streak=saygiStreak(),people=saygiPeople(),total=people.length,bilim=0,sanat=0;people.forEach(function(x){if(coll[x.id]){if(x.kind==='Sanat')sanat++;else bilim++;}});var nudge='';if(read>=6){var totalRead=bilim+sanat;if(totalRead>0&&bilim/totalRead>0.72)nudge='Ağırlık bilimde ('+bilim+') — biraz sanat da keşfet 🎨';else if(totalRead>0&&sanat/totalRead>0.72)nudge='Ağırlık sanatta ('+sanat+') — biraz bilim de keşfet 🔬';}var h='<div class="sg-collect"><div style="display:flex;align-items:center;justify-content:space-between;"><div style="font-size:var(--f-subhead);font-weight:800;color:var(--text);display:flex;align-items:center;gap:7px;">'+iconHtml('trophy',15)+' 100 Öncü Koleksiyonu</div><div class="streak">'+(streak?streak+' gün seri':'&nbsp;')+'</div></div><div class="sg-collect-grid">',todayId=person&&person.id;people.forEach(function(x,idx){var r=coll[x.id],hcl=r?' read':'';if(x.id===todayId)hcl+=' todayd';h+='<button class="d'+hcl+'" onclick="App.openSaygiCollectionPerson(\''+escHtml(x.id)+'\')" title="'+escHtml((idx+1)+'. '+x.name+(r?' · okundu':' · keşfedilmeyi bekliyor'))+'" aria-label="'+escHtml((idx+1)+'. '+x.name+(r?' okundu':' okunmadı')+' · biyografiyi aç')+'"><span>'+(r?'✓':(idx+1))+'</span></button>';});h+='</div><div style="display:flex;justify-content:space-between;align-items:center;font-size:var(--f-caption1);color:var(--muted);"><span>'+read+'/'+total+' okundu</span><span style="color:var(--faith2);font-weight:800;">'+(read>=total?'Tamamlandı 🌟':'Devam')+'</span></div>';if(!read)h+='<div class="sg-collect-empty">Her kutu bir öncüyü temsil ediyor. Bugünün biyografisini “Okudum” diye kaydedince kutusu altın renkle dolacak.</div>';if(nudge)h+='<div class="sg-nudge">'+escHtml(nudge)+'</div>';return h+'</div>';}
  function faithAnnualHeatmapHTML(){var u=stateUi()||{},dta=stateData()||{},now=todayStr(),nowY=new Date().getFullYear(),startY=+(dta.startDate?String(dta.startDate).slice(0,4):nowY),year=+(u.faithHeatYear||nowY);year=Math.max(startY,Math.min(nowY,year));u.faithHeatYear=year;var first=year+'-01-01',last=year+'-12-31',firstDow=(new Date(year,0,1).getDay()+6)%7,cells='',totals={days:0,prayers:0,zikr:0};for(var blank=0;blank<firstDow;blank++)cells+='<span class="c blank" aria-hidden="true"></span>';for(var d=first;d<=last;d=addDays(d,1)){var f=faithDayHeat(d),future=d>now,tip=dateLabelTR(d)+' · '+f.performed+' vakit'+(f.zikr?' · '+f.zikr+' zikir':'');if(f.performed||f.zikr){totals.days++;totals.prayers+=f.performed;totals.zikr+=f.zikr;}cells+='<button class="c'+(future?' future':'')+'" data-l="'+f.level+'" '+(future?'disabled':'onclick="App.openFaithHeatDay(\''+d+'\')"')+' title="'+escHtml(tip)+'" aria-label="'+escHtml(tip)+'"></button>';}var prev=year>startY,next=year<nowY,h='<section class="sg-faith-year"><div class="sg-faith-year-head"><div><strong>'+year+' · Yıllık İbadet Isısı</strong><small>'+totals.days+' aktif gün · '+totals.prayers+' vakit · '+totals.zikr+' zikir</small></div><div><button '+(prev?'onclick="App.faithHeatYear(-1)"':'disabled')+' aria-label="Önceki yıl">‹</button><button '+(next?'onclick="App.faithHeatYear(1)"':'disabled')+' aria-label="Sonraki yıl">›</button></div></div><div class="sg-faith-year-scroll"><div class="sg-faith-months"><span>Oca</span><span>Şub</span><span>Mar</span><span>Nis</span><span>May</span><span>Haz</span><span>Tem</span><span>Ağu</span><span>Eyl</span><span>Eki</span><span>Kas</span><span>Ara</span></div><div class="sg-faith-heat" role="grid" aria-label="'+year+' yıllık ibadet ısı haritası">'+cells+'</div></div><div class="sg-faith-legend"><span>Sakin</span><i data-l="0"></i><i data-l="1"></i><i data-l="2"></i><i data-l="3"></i><i data-l="4"></i><span>Yoğun</span></div><p>Renk, günün kılınan vakit sayısını; zikir kaydı varsa bir kademe daha güçlü ritmi gösterir. Bir güne dokununca gün ayrıntısı açılır.</p></section>';return h;}
  function faithRaporCardHTML(){var k=faithWeekKPIs(todayStr()),streak=zikrCall('zikrStreak',[])||0,pct=k.maxPrays>0?Math.round(k.prays/k.maxPrays*100):0,h='<div class="sg-faith-hero sg-gradient-border sg-glow"><div style="display:flex;align-items:center;justify-content:space-between;gap:10px;"><div><div style="font-size:var(--f-subhead);font-weight:800;color:var(--faith);display:flex;align-items:center;gap:7px;">'+iconHtml('bar-chart',16)+' Bu Haftanın İbadet Ritmi</div><div style="font-size:var(--f-caption1);color:var(--faint);margin-top:2px;">Vakit · cemaat · zikir · seri</div></div><div style="text-align:right;flex-shrink:0;"><div style="font-size:var(--f-title1);font-weight:800;color:var(--faith);">%'+pct+'</div><div style="font-size:var(--f-caption2);color:var(--faint);">kayıtlı vakit payı</div></div></div><div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:8px;"><div class="sg-faith-kpi"><div style="font-size:var(--f-title3);font-weight:800;color:var(--faith);">'+k.prays+'/'+k.maxPrays+'</div><div style="font-size:var(--f-caption2);color:var(--faint);">vakit</div></div><div class="sg-faith-kpi"><div style="font-size:var(--f-title3);font-weight:800;color:var(--faith2);">'+k.cong+'</div><div style="font-size:var(--f-caption2);color:var(--faint);">cemaat</div></div><div class="sg-faith-kpi"><div style="font-size:var(--f-title3);font-weight:800;color:var(--zikr);">'+k.zikrTotal+'</div><div style="font-size:var(--f-caption2);color:var(--faint);">zikir</div></div><div class="sg-faith-kpi"><div style="font-size:var(--f-title3);font-weight:800;color:var(--kandil);">'+(streak||0)+'</div><div style="font-size:var(--f-caption2);color:var(--faint);">seri</div></div></div><div style="display:flex;align-items:flex-end;gap:5px;height:64px;margin-top:4px;">';var dta=stateData()||{},max=1,vals=[];for(var i=6;i>=0;i--){var date=addDays(todayStr(),-i),rec=dta.days&&dta.days[date],c=0,order=prayerValue('PRAYER_ORDER',[]);if(rec&&rec.prayer)order.forEach(function(x){if(rec.prayer[x]&&rec.prayer[x].performed)c++;});vals.push(c);if(c>max)max=c;}vals.forEach(function(v,i2){var hp=max>0?Math.round(v/max*52)+6:6,wd=['Paz','Pzt','Sal','Çar','Per','Cum','Cmt'][new Date(Date.parse(addDays(todayStr(),-6+i2))).getDay()];h+=(v>0?'<span style="font-size:var(--f-caption2);font-weight:700;color:var(--faint);">'+v+'</span>':'')+'<div style="flex:1;display:flex;flex-direction:column;align-items:center;gap:3px;"><div style="width:100%;max-width:24px;height:'+hp+'px;border-radius:6px;background:'+(v>0?'linear-gradient(180deg,var(--faith2),var(--faith))':'var(--icon)')+';transition:height .3s;"></div><span style="font-size:var(--f-caption2);color:'+(i2===6?'var(--faith)':'var(--faint)')+';font-weight:'+(i2===6?'800':'600')+';">'+wd+'</span></div>';});return h+'</div>'+faithAnnualHeatmapHTML()+'</div>';}
  function qiblaHubCardHTML(){var m=qiblaMetrics(prayerCall('prayerLocation',[]),null),loc=m.location||{},h='<button class="sg-qibla-card" onclick="App.openQibla()" aria-label="Kıble pusulasını aç"><span class="sg-qibla-card-dial" aria-hidden="true"><i class="north">K</i><i class="arrow" style="transform:rotate('+m.bearing+'deg)">'+iconHtml('navigation',18)+'</i></span><span class="sg-qibla-card-copy"><small>KIBLE · GERÇEK KUZEY</small><strong>'+m.bearing.toLocaleString('tr-TR')+'° · '+escHtml(m.direction)+'</strong><em>'+escHtml(loc.cityName||'Konum')+' · Kâbe '+m.distanceKm.toLocaleString('tr-TR')+' km</em></span><span class="sg-qibla-card-method"><b>'+iconHtml('route',12)+' Büyük daire</b><em>'+escHtml(qiblaLocationPrecision(m))+'</em></span><span class="sg-qibla-card-action">'+(m.isFallback?'Konumu doğrula':'Pusulayı aç')+' '+iconHtml('chevron-right',15)+'</span></button>';return h;}
function qiblaOverlayHTML(){
  var u=stateUi()||{}, m=qiblaMetrics(prayerCall('prayerLocation',[])||{},u.qiblaHeading), loc=m.location||{}, align=qiblaAlignmentCopy(m);
  var sensor=u.qiblaListening?(u.qiblaSensorSource==='magnetic'?'Manyetik pusula · yerel sapma olabilir':'Mutlak cihaz yönü'):('Sensör kapalı');
  if(u.qiblaAccuracy!=null) sensor+=' · ±'+Math.round(u.qiblaAccuracy)+'°';
  var h='<div id="qibla-overlay" class="qibla-v2-back" onclick="App.closeQibla()">';
  h+='<section id="qibla-dialog" class="qibla-v2-sheet" role="dialog" aria-modal="true" aria-labelledby="qibla-v2-title" tabindex="-1" onkeydown="App.onModalKeydown(event,App.closeQibla)" onclick="event.stopPropagation()">';
  h+='<header class="qibla-v2-head"><div><span>'+iconHtml('compass',14)+' BİLİMSEL YÖN HESABI</span><h2 id="qibla-v2-title">Kıble pusulası</h2><p>Konumdan Kâbe’ye başlangıç büyük-daire azimutu</p></div><button onclick="App.closeQibla()" aria-label="Kıble pusulasını kapat">'+iconHtml('x',18)+'</button></header>';
  h+='<div class="qibla-v2-scroll">';
  h+='<div class="qibla-v2-target"><div><span>HEDEF DOĞRULTU</span><strong>'+m.bearing.toLocaleString('tr-TR')+'°</strong><small>gerçek kuzeyden saat yönünde · '+escHtml(m.direction)+'</small></div><div><span>KÂBE MESAFESİ</span><strong>'+m.distanceKm.toLocaleString('tr-TR')+' km</strong><small>'+escHtml(loc.cityName||'Konum')+' merkezli</small></div></div>';
  h+='<div class="qibla-v2-stage">';
  h+='<div class="qibla-v2-dial" aria-label="Kıble yönü '+m.bearing+' derece"><span class="cardinal n">K</span><span class="cardinal e">D</span><span class="cardinal s">G</span><span class="cardinal w">B</span><span class="qibla-v2-ticks"></span>';
  h+='<span id="qibla-live-needle" class="qibla-v2-needle" style="transform:rotate('+m.relative+'deg)"><i class="tip">'+iconHtml('navigation',25)+'</i><i class="shaft"></i><b>KÂBE</b></span>';
  h+='<span class="qibla-v2-center"><i></i></span></div>';
  h+='<div id="qibla-live-status" class="qibla-v2-alignment '+align.state+'"><span class="signal">'+iconHtml(align.state==='aligned'?'circle-check':'navigation',16)+'</span><div><strong>'+escHtml(align.title)+'</strong><small>'+escHtml(align.detail)+'</small></div></div>';
  h+='</div>';
  h+='<div class="qibla-v2-readings"><div><span>CİHAZ YÖNÜ</span><strong id="qibla-live-heading">'+(m.hasHeading?(((Number(u.qiblaHeading)%360+360)%360).toFixed(1).replace('.',',')+'°'):'—')+'</strong><small id="qibla-live-sensor">'+escHtml(sensor)+'</small></div><div><span>KONUM HASSASİYETİ</span><strong>'+escHtml(qiblaLocationPrecision(m))+'</strong><small>'+(m.isFallback?'GPS ile doğrula':(+loc.lat).toFixed(4)+', '+(+loc.lon).toFixed(4))+'</small></div></div>';
  if(u.qiblaSensorError) h+='<div id="qibla-live-error" class="qibla-v2-error" role="alert">'+iconHtml('triangle-alert',15)+'<span>'+escHtml(u.qiblaSensorError)+'</span></div>'; else h+='<div id="qibla-live-error" class="qibla-v2-error" role="alert" hidden></div>';
  h+='<div class="qibla-v2-actions"><button class="location" onclick="App.fetchPrayerLocationGPS()">'+iconHtml('map-pin',16)+'<span><b>GPS’i yenile</b><small>Yüksek hassasiyetli konum</small></span></button><button id="qibla-sensor-button" class="sensor '+(u.qiblaListening?'on':'')+'" onclick="App.enableQiblaCompass()">'+iconHtml('compass',16)+'<span><b>'+(u.qiblaListening?'Pusula açık':'Canlı pusulayı aç')+'</b><small>'+(u.qiblaListening?'Telefonu düz tut':'Sensör izni gerekir')+'</small></span></button></div>';
  h+='<aside class="qibla-v2-method"><strong>'+iconHtml('info',14)+' Hesap ve sensör sınırları</strong><p>Kâbe koordinatı 21,4225° K · 39,8262° D alınır. Hedef, coğrafi kuzeye göre büyük-daire başlangıç azimutudur. Telefon pusulası metal, mıknatıs, elektronik cihazlar ve manyetik sapmadan etkilenebilir; telefonu sekiz çizerek kalibre et ve kılıftaki mıknatıslardan uzaklaştır.</p></aside>';
  h+='</div></section></div>';
  return h;
}
  function saygiPreviewHubHTML(person,article,done){var u=stateUi()||{},tab=u.faithTab||'oz',body='';if(!zikrVisible()&&tab==='zikir'){tab='oz';u.faithTab='oz';}if(tab==='oncu')body=saygiPreviewCardHTML(person,done,article)+saygiCollectionCardHTML(person);else if(tab==='iman')body=faithCornerCardHTML();else if(tab==='zikir'&&zikrVisible())body=zikrPreview();else if(tab==='rapor')body=faithRaporCardHTML();else body=saygiPreviewCardHTML(person,done,article)+faithCornerCardHTML()+(zikrVisible()?zikrPreview():'');return '<div class="saygi-preview-hub">'+body+'</div>';}
  function faithNavHTML(){var tabs=zikrVisible()?[['oz','Öz'],['oncu','Öncü'],['iman','İman'],['zikir','Zikir'],['rapor','Rapor']]:[['oz','Öz'],['oncu','Öncü'],['iman','İman'],['rapor','Rapor']],u=stateUi()||{},tab=u.faithTab||'oz',icons={oz:'circle',oncu:'trophy',iman:'mosque',zikir:'sparkles',rapor:'chart-column'},h='<nav class="faith-v2-nav" aria-label="İlham ve İbadet bölümleri">';tabs.forEach(function(x){var on=x[0]===tab;h+='<button class="'+(on?'on':'')+'" onclick="App.setFaithTab(\''+x[0]+'\')" aria-current="'+(on?'page':'false')+'"><span>'+iconHtml(icons[x[0]]||'circle',16)+'</span><b>'+x[1]+'</b></button>';});return h+'</nav>';}
  function saygiHTML(){if(!featureLive())return saygiComingSoonHTML();var person=saygiCurrentPerson();if(!person)return '<div class="saygi-empty">'+iconHtml('triangle-alert',24)+' Saygı seçkisi yüklenemedi.</div>';var u=stateUi()||{};if(!u.saygiPersonOpen)saygiEnsureArticle(person);var article=(!u.saygiPersonOpen&&u.saygiArticle&&u.saygiArticle.personId===person.id)?u.saygiArticle:null,done=saygiHasRead(person);return '<section class="saygi-page">'+faithNavHTML()+spiritBarHTML()+qiblaHubCardHTML()+quranHub()+saygiPreviewHubHTML(person,article,done)+'</section>';}
  function saygiArticleBodyHTML(person,article,done,wrapCls,includeReadAction){var heroLead=article.lead,first=article.blocks&&article.blocks[0];if(first&&heroLead&&first.text.slice(0,90)===heroLead.slice(0,90))heroLead='';var h='<article class="'+(wrapCls||'saygi-article')+'"><header class="saygi-hero">'+(article.thumbnail?'<div class="saygi-hero-media"><img src="'+escHtml(article.thumbnail)+'" alt="'+escHtml(article.title)+' portresi" loading="eager" referrerpolicy="no-referrer"><span>Görsel · Wikipedia</span></div>':'<div class="saygi-hero-media is-empty">'+iconHtml('trophy',42)+'<span>Günün ismi</span></div>')+'<div class="saygi-hero-copy"><div class="saygi-tags"><span>'+escHtml(person.kind)+'</span><span>'+escHtml(person.era)+'</span></div><h2>'+escHtml(article.title)+'</h2><div class="saygi-discipline">'+iconHtml(person.kind==='Bilim'?'microscope':'feather',15)+' '+escHtml(person.field)+'</div>'+(article.description?'<p class="saygi-description">'+escHtml(article.description)+'</p>':'')+(heroLead?'<p class="saygi-lead">'+escHtml(heroLead)+'</p>':'')+'<div class="saygi-meta"><span>'+iconHtml('clock',13)+' yaklaşık '+saygiReadMinutes(article)+' dk</span><span>'+iconHtml('book-open',13)+' '+(article.lang==='tr'?'Türkçe Wikipedia':'English Wikipedia')+'</span></div></div></header><div class="saygi-biography">';article.blocks.forEach(function(block){if(!block||!block.text)return;if(block.type==='h')h+='<h3>'+escHtml(block.text)+'</h3>';else if(block.type==='list')h+='<div class="saygi-list-block">'+iconHtml('sparkles',14)+'<span>'+escHtml(block.text)+'</span></div>';else h+='<p>'+escHtml(block.text)+'</p>';});h+='</div><section class="saygi-sources"><div class="saygi-section-title"><span>'+iconHtml('link-2',16)+'</span><div><strong>Kaynakta daha derine in</strong><small>Wikipedia maddesi ve maddede yer alan seçili dış bağlantılar</small></div></div><div class="saygi-source-grid">'+saygiSourceCardHTML(article,null,true);(article.links||[]).forEach(function(link){h+=saygiSourceCardHTML(article,link,false);});return h+'</div></section><footer class="saygi-attribution"><span>'+iconHtml('file-text',13)+'</span><span>Metin <a href="'+escHtml(article.sourceUrl)+'" target="_blank" rel="noopener noreferrer">Wikipedia katkıda bulunanlarından</a> alınır; '+escHtml(article.licenseTitle)+' lisansı ile paylaşılır.</span><a href="'+escHtml(article.licenseUrl)+'" target="_blank" rel="noopener noreferrer" aria-label="Lisans ayrıntısı">'+iconHtml('external-link',13)+'</a></footer>'+(includeReadAction!==false?saygiReadButtonHTML(person,done,article.suffix||''):'')+'</article>';}
  function saygiPersonModalHTML(){var u=stateUi()||{},person=saygiModalPerson();if(!person)return '';var article=(u.saygiArticle&&u.saygiArticle.personId===person.id)?u.saygiArticle:null,done=saygiHasRead(person),people=saygiPeople(),personIndex=people.findIndex(function(x){return x.id===person.id;}),head='<div class="sg-person-ov-head"><div><div class="sg-person-ov-title"><span>'+iconHtml('trophy',16)+'</span>'+escHtml(person.name)+'</div><small class="sg-person-ov-count">'+(personIndex+1)+' / '+people.length+' · Öncü koleksiyonu</small></div><div class="sg-person-ov-nav"><button onclick="App.browseSaygiPerson(-1)" aria-label="Önceki öncü">‹</button><button onclick="App.browseSaygiPerson(1)" aria-label="Sonraki öncü">›</button><button onclick="App.closeSaygiPerson()" aria-label="Kapat">'+iconHtml('x',16)+'</button></div></div>',body='';if(u.saygiLoading||!article){body+='<div style="padding:18px 4px;">';if(u.saygiLoading)body+=saygiLoadingHTML();else body+='<div class="saygi-error"><span>'+iconHtml('cloud-rain',22)+'</span><div><strong>Bugünün kaynağına ulaşamadık.</strong><p>'+escHtml(u.saygiError||'Birazdan yeniden deneyebilirsin.')+'</p><div class="saygi-error-actions"><button onclick="App.refreshSaygi()">'+iconHtml('rotate-ccw',14)+' Yeniden dene</button><a href="'+escHtml(saygiSourceFallback(person))+'" target="_blank" rel="noopener noreferrer">Wikipedia’da aç '+iconHtml('external-link',13)+'</a></div></div></div>';body+='</div>';}else{article=Object.create(article);article.suffix='-modal';body+=saygiArticleBodyHTML(person,article,done,'saygi-article-modal',false);body+='<div id="saygi-read-sentinel-modal" class="saygi-read-sentinel" aria-hidden="true"></div>';}return '<div id="sey-ov-back" class="sg-person-ov-back" onclick="App.closeSaygiPerson()" style="position:fixed;inset:0;z-index:340;background:rgba(44,36,38,0.45);display:flex;align-items:flex-end;justify-content:center;padding:14px;"><div id="sey-ov-card" class="sg-person-ov-card" role="dialog" aria-modal="true" aria-label="Günün öncüsü" tabindex="-1" onkeydown="App.onModalKeydown(event,App.closeSaygiPerson)" onclick="event.stopPropagation()" style="position:relative;width:100%;max-width:520px;height:92vh;max-height:900px;background:var(--modal);border-radius:28px;padding:0;box-shadow:0 -12px 50px rgba(0,0,0,0.22);display:flex;flex-direction:column;overflow:hidden;"><div style="flex-shrink:0;padding:14px 18px 12px;border-bottom:1px solid var(--card-bd);">'+head+'</div><div id="sey-ov-body" class="sg-person-ov-body scroll" style="flex:1;min-height:0;overflow-y:auto;padding:18px 18px 104px;display:flex;flex-direction:column;gap:14px;">'+body+'</div></div></div>';}
  function saygiFloatingReadHTML(){var person=saygiModalPerson();if(!person)return '';var u=stateUi()||{},article=u.saygiArticle&&u.saygiArticle.personId===person.id?u.saygiArticle:null,done=saygiHasRead(person),ready=!!u.saygiReadReady,disabled=!done&&(!article||!ready),sub=done?'Ne okudum kaydını aç':(!article?(u.saygiLoading?'Biyografi hazırlanıyor':'Biyografi yüklenince açılır'):(ready?'Bugünün kaydına ekle':'Yazının sonuna inince açılır'));return '<button id="saygi-read-button-modal" class="sg-person-read-fab'+(done?' is-done':(ready?' is-ready':' is-locked'))+'" '+(disabled?'disabled':'')+' onclick="'+(done?'App.openSaygiReading()':'App.markSaygiRead()')+'" style="position:fixed!important;z-index:2147483640!important;left:50%!important;bottom:24px!important;transform:translateX(-50%)!important;display:flex!important;visibility:visible!important;opacity:'+(disabled?'.72':'1')+'!important;pointer-events:auto!important;box-sizing:border-box!important;width:calc(100vw - 64px)!important;max-width:484px!important;min-height:58px!important;align-items:center!important;justify-content:center!important;gap:10px!important;border:1px solid rgba(255,255,255,.34)!important;border-radius:18px!important;padding:10px 16px calc(10px + env(safe-area-inset-bottom))!important;color:#FFF9EC!important;background:linear-gradient(135deg,#C4A35A,#826936)!important;box-shadow:0 14px 34px rgba(52,39,18,.38)!important;font:inherit!important;cursor:'+(disabled?'not-allowed':'pointer')+'!important;"><span class="saygi-read-button-icon" style="display:inline-flex!important;">'+iconHtml(done?'circle-check':'book-open',20)+'</span><span style="display:flex!important;flex-direction:column!important;align-items:flex-start!important;text-align:left!important;"><strong data-saygi-read-copy style="font-size:var(--f-subhead)!important;line-height:1.1!important;">Okudum</strong><small data-saygi-read-sub style="margin-top:3px!important;color:rgba(255,249,236,.84)!important;font-size:var(--f-caption2)!important;font-weight:700!important;">'+escHtml(sub)+'</small></span></button>';}
  function saygiUnlockReadButton(btn){var u=stateUi()||{};if(!btn||btn.disabled===false&&u.saygiReadReady)return;u.saygiReadReady=true;btn.disabled=false;btn.classList.remove('is-locked');btn.classList.add('is-ready');var copy=btn.querySelector('[data-saygi-read-copy]'),sub=btn.querySelector('[data-saygi-read-sub]');if(copy)copy.textContent='Okudum';if(sub)sub.textContent='Bugünün kaydına ekle';var ic=btn.querySelector('.saygi-read-button-icon');if(ic)ic.innerHTML=iconHtml('circle-check',19);}
  function saygiDisconnectReadObserver(){if(saygiReadObserver){try{saygiReadObserver.disconnect();}catch(e){}saygiReadObserver=null;}}
  function wireSaygiReadGate(sc,suffix){if(!sc)return;suffix=suffix||'';var person=suffix==='-modal'?saygiModalPerson():saygiCurrentPerson(),btn=document.getElementById('saygi-read-button'+suffix),sentinel=document.getElementById('saygi-read-sentinel'+suffix);if(!person||!btn||!sentinel||saygiHasRead(person))return;function unlock(){saygiUnlockReadButton(btn);saygiDisconnectReadObserver();}if(sc.scrollHeight<=sc.clientHeight+32){unlock();return;}if(window.IntersectionObserver){saygiReadObserver=new window.IntersectionObserver(function(entries){for(var i=0;i<entries.length;i++)if(entries[i].isIntersecting){unlock();break;}},{root:sc,threshold:.72});saygiReadObserver.observe(sentinel);}else{var onScroll=function(){if(sc.scrollTop+sc.clientHeight>=sc.scrollHeight-28){sc.removeEventListener('scroll',onScroll);unlock();}};sc.addEventListener('scroll',onScroll,{passive:true});onScroll();}}

  window.SeymaSaygi={
    registerSaygi:registerSaygi,SAYGI_EPOCH:SAYGI_EPOCH,SAYGI_CACHE_PREFIX:SAYGI_CACHE_PREFIX,
    emptySaygiRoot:emptySaygiRoot,ensureSaygiRoot:ensureSaygiRoot,emptySaygi:emptySaygi,ensureSaygiDay:ensureSaygiDay,saygiMarkRead:saygiMarkRead,
    saygiCollection:saygiCollection,saygiReadCount:saygiReadCount,saygiStreak:saygiStreak,saygiPeople:saygiPeople,saygiPositiveMod:saygiPositiveMod,
    saygiPersonForDate:saygiPersonForDate,saygiCurrentPerson:saygiCurrentPerson,saygiPersonById:saygiPersonById,saygiModalPerson:saygiModalPerson,saygiDayKey:saygiDayKey,
    saygiCacheKey:saygiCacheKey,saygiReadCache:saygiReadCache,saygiWriteCache:saygiWriteCache,saygiSafeUrl:saygiSafeUrl,saygiFetchJSON:saygiFetchJSON,
    saygiSummaryUrl:saygiSummaryUrl,saygiHtmlUrl:saygiHtmlUrl,saygiFetchSummary:saygiFetchSummary,saygiLoadSummary:saygiLoadSummary,saygiPlainText:saygiPlainText,
    saygiStopHeading:saygiStopHeading,saygiBioBlocks:saygiBioBlocks,saygiExternalLinks:saygiExternalLinks,saygiArticleFrom:saygiArticleFrom,
    saygiArticleReadableFor:saygiArticleReadableFor,saygiRequestIsCurrent:saygiRequestIsCurrent,saygiLoadArticle:saygiLoadArticle,saygiEnsureArticle:saygiEnsureArticle,
    saygiReadMinutes:saygiReadMinutes,saygiReadingEntry:saygiReadingEntry,saygiHasRead:saygiHasRead,saygiDomainTone:saygiDomainTone,
    faithWeekKPIs:faithWeekKPIs,faithDayHeat:faithDayHeat,qiblaBearing:qiblaBearing,qiblaDistanceKm:qiblaDistanceKm,qiblaDirectionLabel:qiblaDirectionLabel,
    qiblaMetrics:qiblaMetrics,qiblaLocationPrecision:qiblaLocationPrecision,qiblaAlignmentCopy:qiblaAlignmentCopy,qiblaScreenAngle:qiblaScreenAngle,qiblaOverlayHTML:qiblaOverlayHTML,
    saygiSourceFallback:saygiSourceFallback,saygiSourceCardHTML:saygiSourceCardHTML,saygiReadButtonHTML:saygiReadButtonHTML,saygiReadActionHTML:saygiReadActionHTML,
    saygiLoadingHTML:saygiLoadingHTML,saygiComingSoonHTML:saygiComingSoonHTML,faithSummaryBadges:faithSummaryBadges,faithCornerCardHTML:faithCornerCardHTML,
    saygiPreviewCardHTML:saygiPreviewCardHTML,saygiMissionCardHTML:saygiMissionCardHTML,faithCornerInlineHTML:faithCornerInlineHTML,prayerRowHTML:prayerRowHTML,
    hijriTodayStr:hijriTodayStr,kandilBadgeFor:kandilBadgeFor,spiritBarHTML:spiritBarHTML,faithCornerOverlayHTML:faithCornerOverlayHTML,
    saygiCollectionCardHTML:saygiCollectionCardHTML,faithAnnualHeatmapHTML:faithAnnualHeatmapHTML,faithRaporCardHTML:faithRaporCardHTML,qiblaHubCardHTML:qiblaHubCardHTML,
    saygiPreviewHubHTML:saygiPreviewHubHTML,faithNavHTML:faithNavHTML,saygiHTML:saygiHTML,saygiArticleBodyHTML:saygiArticleBodyHTML,saygiPersonModalHTML:saygiPersonModalHTML,
    saygiFloatingReadHTML:saygiFloatingReadHTML,saygiUnlockReadButton:saygiUnlockReadButton,wireSaygiReadGate:wireSaygiReadGate,saygiDisconnectReadObserver:saygiDisconnectReadObserver
  };
})();
